import type {ChallengeSpec} from './lessons';

export type BossPhase={name:string;objective:string;concept:string;starterCode:string;expectedOutput:string;challenge?:ChallengeSpec};
export type Boss={id:string;layer:number;name:string;title:string;intro:string;phases:BossPhase[];rewardXp:number};
const b=(id:string,layer:number,name:string,title:string,intro:string,phases:BossPhase[],rewardXp:number):Boss=>({id,layer,name,title,intro,phases,rewardXp});
export const bosses:Boss[]=[
 b('loop-demon',3,'LOOP DEMON','THERE IS NO EXIT CONDITION.','Survive iteration, control flow, and nested loops.',[
  {name:'THE COUNT',objective:'Produce 1 through 4 exactly once.',concept:'for / range()',starterCode:'for i in range(1, 5):\n    print(i)',expectedOutput:'1\n2\n3\n4',challenge:{required:[/for\s+\w+\s+in\s+range\s*\(/,/range\s*\(\s*1\s*,\s*5\s*\)/]}},
  {name:'THE ESCAPE',objective:'Print only odd values below 6, then stop at 5.',concept:'break / continue',starterCode:'for i in range(1, 6):\n    if i == 5:\n        break\n    if i % 2 == 0:\n        continue\n    print(i)',expectedOutput:'1\n3',challenge:{required:[/break\b/,/continue\b/,/for\s+/]}},
  {name:'THE LABYRINTH',objective:'Print a 2 × 3 coordinate grid without duplicate cells.',concept:'nested loops',starterCode:'for row in range(2):\n    for col in range(3):\n        print(f"{row},{col}")',expectedOutput:'0,0\n0,1\n0,2\n1,0\n1,1\n1,2',challenge:{required:[/for\s+\w+\s+in\s+range\s*\(/,/for\s+\w+\s+in\s+range\s*\(/]}}
 ],100),
 b('function-lord',5,'FUNCTION LORD','RETURN WITH SOMETHING USEFUL.','Parameters, defaults, scope and closures are now weapons.',[
  {name:'THE CONTRACT',objective:'Write a function that accepts a name and returns a greeting.',concept:'parameters / arguments',starterCode:'def greet(name):\n    return f"Hello, {name}"\n\nprint(greet("Ada"))',expectedOutput:'Hello, Ada',challenge:{required:[/def\s+greet\s*\(\s*name\s*\)/,/return\s+/]}},
  {name:'THE SCOPE',objective:'Use a local binding so the function returns 11 without mutating globals.',concept:'LEGB / local scope',starterCode:'count = 10\ndef add():\n    count = 11\n    return count\n\nprint(add())',expectedOutput:'11',challenge:{required:[/def\s+add\s*\(/,/return\s+count/]}},
  {name:'THE CLOSURE',objective:'Return an inner function that remembers its captured value.',concept:'closures',starterCode:'def multiplier(factor):\n    def apply(value):\n        return value * factor\n    return apply\n\ndouble = multiplier(2)\nprint(double(6))',expectedOutput:'12',challenge:{required:[/def\s+multiplier\s*\(/,/def\s+apply\s*\(/,/return\s+apply/]}}
 ],120),
 b('object-overlord',6,'OBJECT OVERLORD','THE OBJECT HAS A METHOD.','Classes, inheritance and polymorphism converge.',[
  {name:'THE FORGE',objective:'Initialize and expose object state.',concept:'class / __init__',starterCode:'class Demon:\n    def __init__(self, name):\n        self.name = name\n\nd = Demon("Astaroth")\nprint(d.name)',expectedOutput:'Astaroth',challenge:{required:[/class\s+Demon\b/,/__init__/,/self\.name/]}},
  {name:'THE BLOODLINE',objective:'Override one method in a subclass and call it through the child.',concept:'inheritance',starterCode:'class Animal:\n    def speak(self):\n        return "noise"\n\nclass Dog(Animal):\n    def speak(self):\n        return "woof"\n\nprint(Dog().speak())',expectedOutput:'woof',challenge:{required:[/class\s+Dog\s*\(\s*Animal\s*\)/,/def\s+speak\s*\(/]}},
  {name:'THE MASK',objective:'Use one interface to handle two concrete implementations.',concept:'polymorphism',starterCode:'class Square:\n    def area(self):\n        return 4\n\nclass Circle:\n    def area(self):\n        return 7\n\nfor shape in (Square(), Circle()):\n    print(shape.area())',expectedOutput:'4\n7',challenge:{required:[/class\s+Square/,/class\s+Circle/,/for\s+shape\s+in/]}}
 ],140),
 b('exception-beast',7,'EXCEPTION BEAST','THE TRACEBACK KNOWS YOUR NAME.','Handle failure without hiding the crime scene.',[
  {name:'THE CATCH',objective:'Catch ValueError and print a recovery message.',concept:'try / except',starterCode:'try:\n    int("hell")\nexcept ValueError:\n    print("recovered")',expectedOutput:'recovered',challenge:{required:[/try\s*:/,/except\s+ValueError\s*:/]}},
  {name:'THE SIGNAL',objective:'Raise ValueError for a negative health value.',concept:'raise',starterCode:'def check_health(hp):\n    if hp < 0:\n        raise ValueError("negative health")\n    return hp\n\ntry:\n    check_health(-1)\nexcept ValueError as exc:\n    print(exc)',expectedOutput:'negative health',challenge:{required:[/raise\s+ValueError\b/,/except\s+ValueError/]}},
  {name:'THE CLEANUP',objective:'Guarantee cleanup code executes even when work fails.',concept:'finally',starterCode:'try:\n    print("work")\n    raise RuntimeError("boom")\nexcept RuntimeError:\n    print("handled")\nfinally:\n    print("cleanup")',expectedOutput:'work\nhandled\ncleanup',challenge:{required:[/finally\s*:/,/except\s+RuntimeError/]}}
 ],140),
 b('concurrency-hydra',9,'CONCURRENCY HYDRA','EVERY HEAD SHARES STATE.','Threads, locks and async scheduling test your discipline.',[
  {name:'THE RACE',objective:'Make the shared counter deterministic in this small threaded exercise.',concept:'shared state / race conditions',starterCode:'import threading\n\nlock = threading.Lock()\ncount = 0\ndef bump():\n    global count\n    with lock:\n        count += 1\n\nthreads = [threading.Thread(target=bump) for _ in range(4)]\nfor t in threads: t.start()\nfor t in threads: t.join()\nprint(count)',expectedOutput:'4',challenge:{required:[/threading\.Lock\s*\(/,/with\s+lock\s*:/]}},
  {name:'THE LOCK',objective:'Protect the critical section with a context-managed lock.',concept:'threading.Lock',starterCode:'import threading\nlock = threading.Lock()\nvalue = 0\nwith lock:\n    value += 1\nprint(value)',expectedOutput:'1',challenge:{required:[/threading\.Lock\s*\(/,/with\s+lock\s*:/]}},
  {name:'THE AWAIT',objective:'Await a coroutine and print its result.',concept:'async / await',starterCode:'import asyncio\n\nasync def work():\n    return "done"\n\nasync def main():\n    result = await work()\n    print(result)\n\nasyncio.run(main())',expectedOutput:'done',challenge:{required:[/async\s+def\s+main/,/await\s+work\s*\(/,/asyncio\.run\s*\(/]}}
 ],180),
 b('memory-reaper',10,'MEMORY REAPER','REFERENCES HAVE CONSEQUENCES.','Separate language semantics from CPython memory behavior.',[
  {name:'IDENTITY',objective:'Show that equal values need not share identity.',concept:'== / is',starterCode:'a = [1, 2]\nb = [1, 2]\nprint(a == b)\nprint(a is b)',expectedOutput:'True\nFalse',challenge:{required:[/==/,/\bis\b/]}},
  {name:'LIFETIME',objective:'Demonstrate aliases keep the same object reachable.',concept:'references / lifetime',starterCode:'items = ["torch"]\nalias = items\nalias.append("key")\nprint(items)',expectedOutput:"['torch', 'key']",challenge:{required:[/alias\s*=\s*items/,/alias\.append\s*\(/]}},
  {name:'THE COLLECTOR',objective:'Create a reference cycle and then drop the external references.',concept:'GC / CPython',starterCode:'import gc\n\na = []\na.append(a)\nprint(len(a))\na = None\ngc.collect()\nprint("cycle released")',expectedOutput:'1\ncycle released',challenge:{required:[/import\s+gc/,/gc\.collect\s*\(/]}}
 ],200),
 b('cpython-core',12,'CPYTHON CORE DEMON','EXPLAIN THE MACHINE BENEATH THE LANGUAGE.','Advanced runtime questions require version labels and evidence.',[
  {name:'BYTECODE',objective:'Inspect a compiled function with dis without assuming opcode names are universal.',concept:'dis / code objects',starterCode:'import dis\n\ndef add(a, b):\n    return a + b\n\ndis.dis(add)',expectedOutput:'',challenge:{required:[/import\s+dis/,/def\s+add\s*\(/,/dis\.dis\s*\(/]}},
  {name:'OBJECTS',objective:'Inspect the type of a Python object while keeping C-level claims explicit.',concept:'PyObject / C API',starterCode:'value = object()\nprint(type(value).__name__)\nprint("PyObject is a CPython C-level concept")',expectedOutput:'object\nPyObject is a CPython C-level concept',challenge:{required:[/type\s*\(/,/PyObject/] }},
  {name:'THE CORE',objective:'Use a small timing probe and label implementation-sensitive behavior honestly.',concept:'CPython 3.13+ internals',starterCode:'import timeit\n\nseconds = timeit.timeit("sum(range(10))", number=100)\nprint(seconds >= 0)\nprint("Benchmark results depend on workload, platform, and build")',expectedOutput:'True\nBenchmark results depend on workload, platform, and build',challenge:{required:[/timeit\.timeit\s*\(/,/workload,\s*platform,\s*and\s*build/]}}
 ],300),
];
export function bossForLayer(layer:number):Boss|undefined{return bosses.find(boss=>boss.layer===layer)}
