export type ChallengeSpec={
  required?:RegExp[];
  forbidden?:RegExp[];
  harness?:string;
  expected?:string;
  validator?:(source:string,stdout:string)=>boolean;
};
export type Lesson={id:string;layer:number;topic:string;title:string;brief:string;explanation:string;roast:string;difficulty:'BEGINNER'|'INTERMEDIATE'|'ADVANCED';minutes:number;starterCode:string;expectedOutput:string;hints:string[];challenge?:ChallengeSpec};
const c=(expected:string,harness?:string,required:RegExp[]=[],forbidden:RegExp[]=[])=>({expected,harness,required,forbidden});
export const lessonCatalog:Lesson[]=[
{ id:'l1_print',layer:1,topic:'print()',title:'SPEAK, MORTAL.',brief:'Teach the machine its first word.',explanation:'print() writes values to standard output. Strings are text values, usually written inside quotes.',roast:'You have discovered communication. Humanity can now blame the machine properly.',difficulty:'BEGINNER',minutes:8,starterCode:'# Your first spell\nprint("hello, hell")',expectedOutput:'hello, hell',hints:['Call print() with a string.','Keep the exact target text inside quotes.'],challenge:c('hello, hell',undefined,[/print\s*\(/]) },
{ id:'l1_comments',layer:1,topic:'comments',title:'LEAVE A NOTE FOR YOUR FUTURE SELF.',brief:'Write comments that explain intent, not the obvious.',explanation:'A # starts a comment. Comments are for humans; Python ignores them when executing code.',roast:'Future you has a memory leak. Leave documentation.',difficulty:'BEGINNER',minutes:7,starterCode:'# Explain the spell here\nprint("documented")',expectedOutput:'documented',hints:['Start a comment with #.','The comment should not change the output.'],challenge:c('documented',undefined,[/#/]) },
{ id:'l1_variables',layer:1,topic:'variables',title:'NAME THE DEMON.',brief:'Bind a value to a name and use it.',explanation:'Assignment binds a name to an object. The name is a reference, not a tiny box containing bytes.',roast:'Please resist calling every variable temp_final_final2.',difficulty:'BEGINNER',minutes:10,starterCode:'soul = 13\nprint(soul)',expectedOutput:'13',hints:['Use = for assignment.','The required variable name is soul.'],challenge:c('13',undefined,[/\bsoul\s*=/]) },
{ id:'l1_strings',layer:1,topic:'strings',title:'TAME THE TEXT BEAST.',brief:'Combine and transform text.',explanation:'Strings are immutable sequences of text. Concatenation with + creates a new string.',roast:'At least strings usually fail politely.',difficulty:'BEGINNER',minutes:10,starterCode:'name = "hell"\nprint("python " + name)',expectedOutput:'python hell',hints:['Use + to concatenate strings.','Keep the spaces intentional.'],challenge:c('python hell',undefined,[/\+/]) },
{ id:'l1_numbers',layer:1,topic:'numbers',title:'COUNT THE DAMAGE.',brief:'Perform arithmetic with integers and floats.',explanation:'Python numbers support arithmetic expressions; int values have arbitrary precision in ordinary Python semantics.',roast:'Math without opening Excel. A dangerous power.',difficulty:'BEGINNER',minutes:10,starterCode:'damage = 7\nbonus = 5\nprint(damage + bonus)',expectedOutput:'12',hints:['Add the two variables.','Print the expression result.'],challenge:c('12',undefined,[/damage\s*\+\s*bonus/]) },
{ id:'l1_booleans',layer:1,topic:'bool',title:'JUDGE THE TRUTH.',brief:'Use True and False as control values.',explanation:'bool has two values: True and False. Comparisons produce boolean results.',roast:'Binary morality. Finally, a simple ethical system.',difficulty:'BEGINNER',minutes:9,starterCode:'ready = True\nprint(ready)',expectedOutput:'True',hints:['Use the capitalized boolean literal True.','Print the boolean value.'],challenge:c('True',undefined,[/True/]) },
{ id:'l1_input',layer:1,topic:'input()',title:'ASK THE MORTAL.',brief:'Read text from a user.',explanation:'input() reads a line and returns a string. Convert explicitly when you need a number.',roast:'The computer asks you a question. You are now in the feedback loop.',difficulty:'BEGINNER',minutes:12,starterCode:'name = "heretic"\nprint("Welcome", name)',expectedOutput:'Welcome heretic',hints:['print() can receive multiple values.','The target includes one space.'],challenge:c('Welcome heretic',undefined,[/print\s*\(/]) },
{ id:'l1_conversion',layer:1,topic:'type conversion',title:'CHANGE THE SHAPE.',brief:'Convert text into a number.',explanation:'int(), float(), and str() explicitly convert values when the conversion is valid.',roast:'Because "42" and 42 are not the same creature.',difficulty:'BEGINNER',minutes:10,starterCode:'raw = "42"\nvalue = int(raw)\nprint(value + 8)',expectedOutput:'50',hints:['Convert raw with int().','Then add 8.'],challenge:c('50',undefined,[/int\s*\(/]) },

{ id:'l2_if',layer:2,topic:'if/elif/else',title:'CHOOSE YOUR FATE.',brief:'Branch on a condition.',explanation:'if executes a suite when its condition is truthy. elif and else offer alternate paths.',roast:'Straight-line code was apparently too peaceful.',difficulty:'BEGINNER',minutes:12,starterCode:'hp = 10\nif hp > 0:\n    print("alive")',expectedOutput:'alive',hints:['Compare hp with zero.','Indent the body.'],challenge:c('alive',undefined,[/\bif\b/,/hp\s*>\s*0/]) },
{ id:'l2_comparison',layer:2,topic:'comparisons',title:'COMPARE WITHOUT GUESSING.',brief:'Use comparison operators precisely.',explanation:'== compares values; !=, <, <=, >, and >= compare according to the operand types.',roast:'Boolean courtroom drama. Evidence required.',difficulty:'BEGINNER',minutes:10,starterCode:'print(7 >= 7)\nprint(7 == 8)',expectedOutput:'True\nFalse',hints:['Use >= for the first comparison.','Use == for value equality.'],challenge:c('True\nFalse',undefined,[/>=|==/]) },
{ id:'l2_logical',layer:2,topic:'logical operators',title:'STACK THE CONDITIONS.',brief:'Combine conditions with and, or, and not.',explanation:'and and or combine boolean contexts with short-circuit evaluation; not negates truth.',roast:'Now the branches have branches. Excellent.',difficulty:'BEGINNER',minutes:12,starterCode:'hp = 10\npoisoned = False\nprint(hp > 0 and not poisoned)',expectedOutput:'True',hints:['Both conditions must be true.','not flips poisoned.'],challenge:c('True',undefined,[/\band\b/,/\bnot\b/]) },
{ id:'l2_nested',layer:2,topic:'nested conditions',title:'THE BRANCH WITHIN THE BRANCH.',brief:'Handle a decision tree without losing indentation.',explanation:'Nested if statements are simply suites inside other suites. Indentation defines their block structure.',roast:'Indentation is now load-bearing. Do not freestyle.',difficulty:'BEGINNER',minutes:14,starterCode:'hp = 10\nshield = True\nif hp > 0:\n    if shield:\n        print("protected")',expectedOutput:'protected',hints:['Keep the second if inside the first.','The print must be inside both blocks.'],challenge:c('protected',undefined,[/if\s+hp/,/if\s+shield/]) },

{ id:'l3_for',layer:3,topic:'for',title:'ITERATE OR PERISH.',brief:'Repeat work over an iterable.',explanation:'for loops pull items from an iterable and bind each item to the loop target in sequence.',roast:'Copy-paste is not a loop. It is an SOS signal.',difficulty:'BEGINNER',minutes:12,starterCode:'for i in range(3):\n    print(i)',expectedOutput:'0\n1\n2',hints:['range(3) yields 0, 1, 2.','Print the loop variable.'],challenge:c('0\n1\n2',undefined,[/\bfor\b/,/range\s*\(/]) },
{ id:'l3_while',layer:3,topic:'while',title:'FEED THE LOOP.',brief:'Repeat while a condition stays true.',explanation:'while evaluates a condition before each iteration and stops when the condition becomes false.',roast:'A loop with no exit plan is called a production incident.',difficulty:'BEGINNER',minutes:14,starterCode:'n = 3\nwhile n > 0:\n    print(n)\n    n -= 1',expectedOutput:'3\n2\n1',hints:['Change n each iteration.','Stop when n reaches zero.'],challenge:c('3\n2\n1',undefined,[/\bwhile\b/,/n\s*-=/]) },
{ id:'l3_range',layer:3,topic:'range()',title:'SUMMON THE RANGE.',brief:'Control start, stop, and step.',explanation:'range() produces an immutable arithmetic progression object used commonly for iteration.',roast:'Off-by-one errors have entered the chat.',difficulty:'BEGINNER',minutes:12,starterCode:'print(list(range(2, 7, 2)))',expectedOutput:'[2, 4, 6]',hints:['The stop value is exclusive.','Use start=2, stop=7, step=2.'],challenge:c('[2, 4, 6]',undefined,[/range\s*\(/]) },
{ id:'l3_break',layer:3,topic:'break',title:'ESCAPE THE LOOP.',brief:'Exit a loop at exactly the right time.',explanation:'break terminates the innermost loop immediately.',roast:'Sometimes quitting is the correct control flow.',difficulty:'BEGINNER',minutes:12,starterCode:'for n in range(10):\n    if n == 3:\n        break\nprint(n)',expectedOutput:'3',hints:['Break when n equals 3.','The break belongs inside the loop.'],challenge:c('3',undefined,[/\bbreak\b/,/n\s*==\s*3/]) },
{ id:'l3_continue',layer:3,topic:'continue',title:'SKIP WITHOUT STOPPING.',brief:'Skip one iteration while keeping the loop alive.',explanation:'continue jumps to the next iteration of the innermost loop.',roast:'Selective avoidance. A developer tradition.',difficulty:'BEGINNER',minutes:12,starterCode:'for n in range(5):\n    if n == 2:\n        continue\n    print(n)',expectedOutput:'0\n1\n3\n4',hints:['Continue when n is two.','Keep printing other values.'],challenge:c('0\n1\n3\n4',undefined,[/\bcontinue\b/]) },

{ id:'l4_lists',layer:4,topic:'lists',title:'OPEN THE GRAVEYARD.',brief:'Store and mutate ordered values.',explanation:'Lists are mutable sequences. Indexing starts at zero and out-of-range access raises IndexError.',roast:'A container you can mutate later. What could possibly go wrong?',difficulty:'BEGINNER',minutes:14,starterCode:'loot = ["torch", "key"]\nloot.append("potion")\nprint(loot[2])',expectedOutput:'potion',hints:['append adds to the end.','The third item is index 2.'],challenge:c('potion',undefined,[/append\s*\(/]) },
{ id:'l4_tuples',layer:4,topic:'tuples',title:'LOCK THE LOADOUT.',brief:'Use an immutable sequence.',explanation:'Tuples are immutable sequences. They can contain mutable objects, but the tuple structure itself cannot be changed.',roast:'Same container, fewer opportunities for chaos.',difficulty:'BEGINNER',minutes:12,starterCode:'coords = (3, 4)\nprint(coords[0] + coords[1])',expectedOutput:'7',hints:['Keep the values in a tuple.','Index the tuple like a sequence.'],challenge:c('7',undefined,[/\(/,/\)/]) },
{ id:'l4_sets',layer:4,topic:'sets',title:'ERASE THE DUPLICATES.',brief:'Collect unique values.',explanation:'Sets are unordered collections of distinct hashable elements.',roast:'Duplicates deleted. Your spreadsheet just felt threatened.',difficulty:'BEGINNER',minutes:14,starterCode:'souls = {1, 1, 2, 3}\nprint(len(souls))',expectedOutput:'3',hints:['Sets remove duplicate elements.','len() counts remaining values.'],challenge:c('3',undefined,[/\{/,/len\s*\(/]) },
{ id:'l4_dicts',layer:4,topic:'dictionaries',title:'NAME THE TREASURES.',brief:'Map keys to values.',explanation:'Dictionaries map hashable keys to values. Keys must obey hashing/equality requirements.',roast:'Key-value pairs. Finally, bureaucracy with a purpose.',difficulty:'BEGINNER',minutes:16,starterCode:'stats = {"hp": 99}\nprint(stats["hp"])',expectedOutput:'99',hints:['Use a string key.','Index the dictionary with stats["hp"].'],challenge:c('99',undefined,[/\[\s*["\']hp/]) },
{ id:'l4_slicing',layer:4,topic:'slicing',title:'CUT THE SEQUENCE.',brief:'Select a range without mutating the original.',explanation:'Sequence slicing creates a new sequence representing the requested range.',roast:'Precision surgery, but with brackets.',difficulty:'BEGINNER',minutes:14,starterCode:'items = [0, 1, 2, 3, 4]\nprint(items[1:4])',expectedOutput:'[1, 2, 3]',hints:['The stop index is exclusive.','Start at index 1 and stop before 4.'],challenge:c('[1, 2, 3]',undefined,[/\[1:4\]/]) },

{ id:'l5_functions',layer:5,topic:'functions',title:'FORGE A FUNCTION.',brief:'Turn repeated logic into a callable spell.',explanation:'A function packages behavior. Parameters receive arguments and return sends a value back.',roast:'Now stop copy-pasting your bug into five locations.',difficulty:'BEGINNER',minutes:15,starterCode:'def damage(base, bonus):\n    return base + bonus\n\nprint(damage(7, 5))',expectedOutput:'12',hints:['Define two parameters.','Return their sum.'],challenge:c('12','print(damage(7, 5))',[/def\s+damage/]) },
{ id:'l5_params',layer:5,topic:'parameters',title:'WRITE THE CONTRACT.',brief:'Separate parameters from arguments.',explanation:'Parameters are names in a function definition; arguments are values supplied at the call site.',roast:'A contract. Read it before signing.',difficulty:'BEGINNER',minutes:14,starterCode:'def greet(name):\n    return "Hi " + name\n\nprint(greet("Ada"))',expectedOutput:'Hi Ada',hints:['name is the parameter.','Ada is the argument.'],challenge:c('Hi Ada','print(greet("Ada"))',[/def\s+greet\s*\(\s*name/]) },
{ id:'l5_defaults',layer:5,topic:'default arguments',title:'DEFAULTS HAVE CONSEQUENCES.',brief:'Use default arguments without mutable-state traps.',explanation:'Default expressions are evaluated when the function is defined. Mutable defaults can preserve state across calls.',roast:'The function remembers. You did not ask it to.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'def add(item, bucket=None):\n    if bucket is None:\n        bucket = []\n    bucket.append(item)\n    return bucket\n\nprint(add("fire"))',expectedOutput:"['fire']",hints:['Use None as the sentinel.','Create a new list inside the function.'],challenge:c("['fire']",'print(add("fire"))',[ /bucket\s*=\s*None/,/bucket\s*is\s*None/ ]) },
{ id:'l5_args_kwargs',layer:5,topic:'*args/**kwargs',title:'OPEN THE ARGUMENT FLOODGATES.',brief:'Accept arbitrary positional and keyword arguments.',explanation:'*args gathers extra positional arguments into a tuple; **kwargs gathers extra keyword arguments into a dictionary.',roast:'One function signature, many regrets.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'def pack(*args, **kwargs):\n    return len(args), sorted(kwargs)\n\nprint(pack(1, 2, mode="hard"))',expectedOutput:"(2, ['mode'])",hints:['Use *args and **kwargs in the definition.','Return the count and keyword names.'],challenge:c("(2, ['mode'])",'print(pack(1, 2, mode="hard"))',[/\*args/,/\*\*kwargs/]) },
{ id:'l5_scope',layer:5,topic:'scope',title:'FIND THE BINDING.',brief:'Predict which name a function resolves.',explanation:'Python resolves names through lexical scopes; local, enclosing, global, and built-in scopes matter.',roast:'The variable exists. The question is whether Python can see it.',difficulty:'INTERMEDIATE',minutes:20,starterCode:'x = "global"\ndef show():\n    x = "local"\n    return x\nprint(show())',expectedOutput:'local',hints:['A local binding wins inside the function.','The global x still exists outside it.'],challenge:c('local','print(show())',[/def\s+show/,/x\s*=\s*["\']local/]) },
{ id:'l5_closures',layer:5,topic:'closures',title:'TRAP STATE IN A CLOSURE.',brief:'Let an inner function remember an enclosing binding.',explanation:'A closure is a function that retains access to bindings from an enclosing scope.',roast:'You wanted hidden state. Python gave you a function that remembers.',difficulty:'ADVANCED',minutes:22,starterCode:'def make_counter():\n    n = 0\n    def next_value():\n        nonlocal n\n        n += 1\n        return n\n    return next_value\n\nc = make_counter()\nprint(c(), c())',expectedOutput:'1 2',hints:['The inner function needs nonlocal to rebind n.','Return the inner function.'],challenge:c('1 2','print(c(), c())',[/nonlocal\s+n/,/return\s+next_value/]) },

{ id:'l6_classes',layer:6,topic:'classes',title:'RAISE THE CLASS.',brief:'Define a class and construct an instance.',explanation:'A class defines attributes and behavior. Instantiating it creates an object instance.',roast:'You have built a mold for future bugs.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'class Demon:\n    pass\n\nprint(type(Demon()).__name__)',expectedOutput:'Demon',hints:['Define a class named Demon.','Instantiate it with Demon().'],challenge:c('Demon',undefined,[/class\s+Demon/]) },
{ id:'l6_init',layer:6,topic:'__init__',title:'ARM THE OBJECT.',brief:'Initialize instance state.',explanation:'__init__ is called after an instance is created to initialize it.',roast:'The object now has paperwork.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'class Demon:\n    def __init__(self, name):\n        self.name = name\n\nprint(Demon("Pythonsura").name)',expectedOutput:'Pythonsura',hints:['Assign to self.name.','Pass the name at construction time.'],challenge:c('Pythonsura',undefined,[/__init__/,/self\.name/]) },
{ id:'l6_methods',layer:6,topic:'methods',title:'GIVE THE OBJECT A VOICE.',brief:'Define and call an instance method.',explanation:'Instance methods receive the instance conventionally through self.',roast:'The object has learned to speak. Terrible news.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'class Demon:\n    def speak(self):\n        return "roar"\nprint(Demon().speak())',expectedOutput:'roar',hints:['Define speak(self).','Return the target text.'],challenge:c('roar',undefined,[/def\s+speak\s*\(\s*self/]) },
{ id:'l6_inheritance',layer:6,topic:'inheritance',title:'INHERIT THE CURSE.',brief:'Reuse behavior through a subclass.',explanation:'A subclass can inherit attributes and methods from a base class and add or override behavior.',roast:'Your bug now has a parent class.',difficulty:'INTERMEDIATE',minutes:20,starterCode:'class Demon:\n    def roar(self): return "roar"\nclass LoopDemon(Demon):\n    pass\nprint(LoopDemon().roar())',expectedOutput:'roar',hints:['Subclass Demon.','Inherited methods remain available.'],challenge:c('roar',undefined,[/class\s+LoopDemon\s*\(\s*Demon\s*\)/]) },
{ id:'l6_polymorphism',layer:6,topic:'polymorphism',title:'SAME CALL, DIFFERENT BEHAVIOR.',brief:'Use a common interface across objects.',explanation:'Polymorphism lets code operate through a shared protocol while objects provide their own behavior.',roast:'Different demons, same method name. Management is thrilled.',difficulty:'ADVANCED',minutes:22,starterCode:'class Fire:\n    def attack(self): return "burn"\nclass Ice:\n    def attack(self): return "freeze"\nfor spell in (Fire(), Ice()): print(spell.attack())',expectedOutput:'burn\nfreeze',hints:['Give both classes an attack method.','Iterate over both objects.'],challenge:c('burn\nfreeze',undefined,[/class\s+Fire/,/class\s+Ice/,/def\s+attack/]) },
{ id:'l6_encapsulation',layer:6,topic:'encapsulation',title:'HIDE A STATE VARIABLE.',brief:'Use name mangling and expose deliberate behavior.',explanation:'Double-underscore attributes trigger name mangling in classes. This is not security; it is a mechanism for reducing accidental name collisions.',roast:'Private-ish. Python refuses to promise a vault.',difficulty:'ADVANCED',minutes:22,starterCode:'class Vault:\n    def __init__(self):\n        self.__secret = 42\n    def reveal(self):\n        return self.__secret\nprint(Vault().reveal())',expectedOutput:'42',hints:['Use a double underscore attribute.','Expose it through a method.'],challenge:c('42',undefined,[/self\.__secret/,/def\s+reveal/]) },

{ id:'l7_exceptions',layer:7,topic:'exceptions',title:'KNOW THE FAILURE.',brief:'Trigger and identify a specific exception.',explanation:'Exceptions represent abnormal control flow. Catch only failures you know how to handle.',roast:'The traceback is not yelling. It is documenting your crimes.',difficulty:'INTERMEDIATE',minutes:16,starterCode:'try:\n    int("hell")\nexcept ValueError:\n    print("ValueError")',expectedOutput:'ValueError',hints:['int("hell") raises ValueError.','Catch that exact type.'],challenge:c('ValueError',undefined,[/ValueError/]) },
{ id:'l7_try_except',layer:7,topic:'try/except',title:'CATCH WITHOUT HIDING EVERYTHING.',brief:'Handle one expected failure and preserve clarity.',explanation:'try/except lets code handle selected exception types. Broad catches can hide unrelated bugs.',roast:'Catching Exception is not a debugging strategy.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'try:\n    value = int("9x")\nexcept ValueError:\n    print("invalid")',expectedOutput:'invalid',hints:['Catch ValueError.','Print a clear message.'],challenge:c('invalid',undefined,[/try\s*:/,/except\s+ValueError/]) },
{ id:'l7_finally',layer:7,topic:'finally',title:'CLEAN UP THE CRIME SCENE.',brief:'Run cleanup regardless of success or failure.',explanation:'finally runs as control leaves the try statement, whether normally or through an exception in the handled cases.',roast:'The cleanup crew arrives even when you fail spectacularly.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'try:\n    print("work")\nfinally:\n    print("cleanup")',expectedOutput:'work\ncleanup',hints:['Put cleanup in finally.','The finally suite still executes.'],challenge:c('work\ncleanup',undefined,[/finally\s*:/]) },
{ id:'l7_raise',layer:7,topic:'raise',title:'THROW YOUR OWN TRACEBACK.',brief:'Raise an explicit exception for invalid input.',explanation:'raise deliberately propagates an exception instance or type.',roast:'When the program must complain, make it complain accurately.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'def require_positive(n):\n    if n <= 0:\n        raise ValueError("must be positive")\n    return n\ntry:\n    require_positive(0)\nexcept ValueError as exc:\n    print(exc)',expectedOutput:'must be positive',hints:['Raise ValueError.','Give it a useful message.'],challenge:c('must be positive',undefined,[/raise\s+ValueError/]) },
{ id:'l7_tracebacks',layer:7,topic:'tracebacks',title:'READ THE CRIME SCENE.',brief:'Use a traceback to locate the failing operation.',explanation:'Tracebacks show the call chain and the exception at the point where execution failed.',roast:'Read from the bottom up. Your dignity will survive.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'def explode():\n    return 1 / 0\n\ntry:\n    explode()\nexcept ZeroDivisionError as exc:\n    print(type(exc).__name__)',expectedOutput:'ZeroDivisionError',hints:['Inspect the exception type.','Tracebacks show where the failure occurred.'],challenge:c('ZeroDivisionError',undefined,[/type\s*\(/]) },
{ id:'l7_debugging',layer:7,topic:'debugging',title:'DEBUG BY HYPOTHESIS.',brief:'Turn a bug into a sequence of testable claims.',explanation:'A useful debugging loop is reproduce, observe, isolate, change one thing, and verify.',roast:'Stop clicking Run until reality changes.',difficulty:'ADVANCED',minutes:20,starterCode:'value = [1, 2]\nprint(value[0])\n# Change one thing at a time and verify the hypothesis.',expectedOutput:'1',hints:['Make the smallest change that tests one hypothesis.','Do not rewrite the whole program.'],challenge:c('1') },

{ id:'l8_iterators',layer:8,topic:'iterators',title:'WALK THE ITERATOR.',brief:'Understand next() and StopIteration.',explanation:'An iterator implements iteration state and provides values through __next__ until StopIteration.',roast:'The object can remember where you left off. Horrifyingly useful.',difficulty:'ADVANCED',minutes:22,starterCode:'it = iter([10, 20])\nprint(next(it))\nprint(next(it))',expectedOutput:'10\n20',hints:['iter(sequence) returns an iterator.','next() requests one value.'],challenge:c('10\n20',undefined,[/iter\s*\(/,/next\s*\(/]) },
{ id:'l8_generators',layer:8,topic:'generators',title:'SUMMON LAZY VALUES.',brief:'Produce values one at a time with yield.',explanation:'Generator functions return generator objects and suspend at each yield until resumed.',roast:'The data mountain has become a stream. Much healthier.',difficulty:'ADVANCED',minutes:22,starterCode:'def numbers():\n    yield 1\n    yield 2\nprint(list(numbers()))',expectedOutput:'[1, 2]',hints:['Use yield.','Convert the generator to a list for display.'],challenge:c('[1, 2]','print(list(numbers()))',[/yield\s+/]) },
{ id:'l8_decorators',layer:8,topic:'decorators',title:'WRAP THE SPELL.',brief:'Transform a callable with a decorator.',explanation:'A decorator receives a callable and returns another callable, commonly used to add behavior around a function.',roast:'Congratulations. Your function now has middleware.',difficulty:'ADVANCED',minutes:24,starterCode:'def loud(fn):\n    def wrapper():\n        return fn().upper()\n    return wrapper\n\n@loud\ndef greet():\n    return "hello"\n\nprint(greet())',expectedOutput:'HELLO',hints:['Return the wrapper from the decorator.','Apply it with @loud.'],challenge:c('HELLO',undefined,[/def\s+loud/,/@loud/]) },
{ id:'l8_context',layer:8,topic:'context managers',title:'ENTER WITH CONTROL.',brief:'Use with to guarantee structured setup and cleanup.',explanation:'A context manager coordinates entering and exiting a block, commonly via __enter__ and __exit__.',roast:'Your resources deserve an exit strategy.',difficulty:'ADVANCED',minutes:24,starterCode:'from contextlib import nullcontext\nwith nullcontext("ready") as value:\n    print(value)',expectedOutput:'ready',hints:['Use a with statement.','The context manager binds the value on entry.'],challenge:c('ready',undefined,[/\bwith\b/]) },
{ id:'l8_imports',layer:8,topic:'modules and imports',title:'OPEN THE MODULE PORTAL.',brief:'Import code deliberately.',explanation:'import binds module names in the importing scope. Python packages organize importable modules.',roast:'Someone else already wrote the function. Use it.',difficulty:'INTERMEDIATE',minutes:18,starterCode:'import math\nprint(math.sqrt(16))',expectedOutput:'4.0',hints:['Import math.','Use math.sqrt.'],challenge:c('4.0',undefined,[/import\s+math/,/math\.sqrt/]) },
{ id:'l8_descriptors',layer:8,topic:'descriptors',title:'INTERCEPT ATTRIBUTE ACCESS.',brief:'See how descriptors can customize attribute behavior.',explanation:'A descriptor implements methods such as __get__, __set__, or __delete__ and participates in attribute access.',roast:'The attribute lookup has a bouncer.',difficulty:'ADVANCED',minutes:28,starterCode:'class Echo:\n    def __get__(self, obj, owner):\n        return "echo"\nclass Room:\n    sound = Echo()\nprint(Room().sound)',expectedOutput:'echo',hints:['Define __get__.','Attach an Echo instance to a class attribute.'],challenge:c('echo',undefined,[/__get__/,/sound\s*=\s*Echo/]) },
{ id:'l8_mro',layer:8,topic:'MRO',title:'SURVIVE METHOD LOOKUP.',brief:'Inspect Python’s method resolution order.',explanation:'Python uses a method resolution order to determine where inherited attributes are found in a class hierarchy.',roast:'Multiple inheritance has entered the building. Nobody is calm.',difficulty:'ADVANCED',minutes:26,starterCode:'class A: pass\nclass B(A): pass\nprint([c.__name__ for c in B.mro()])',expectedOutput:"['B', 'A', 'object']",hints:['Use the mro() method.','The returned sequence contains classes in lookup order.'],challenge:c("['B', 'A', 'object']",undefined,[/\.mro\s*\(/]) },

{ id:'l9_threading',layer:9,topic:'threading',title:'SPAWN THE THREADS.',brief:'Create and join threads safely.',explanation:'threading exposes OS-level threads around Python execution; coordination and shared-state design matter.',roast:'Parallelism is not permission to stop thinking.',difficulty:'ADVANCED',minutes:26,starterCode:'import threading\n\nseen=[]\ndef work(): seen.append("done")\n\nt=threading.Thread(target=work)\nt.start(); t.join()\nprint(seen)',expectedOutput:"['done']",hints:['Start the thread, then join it.','Keep shared state simple for this exercise.'],challenge:c("['done']",undefined,[/threading\.Thread/,/\.join\s*\(/]) },
{ id:'l9_multiprocessing',layer:9,topic:'multiprocessing',title:'FORK THE WORKLOAD.',brief:'Understand process-based parallel execution.',explanation:'multiprocessing creates separate processes with separate memory spaces, enabling true parallel CPU execution when the platform and workload permit.',roast:'Now the bug has a passport and its own address space.',difficulty:'ADVANCED',minutes:28,starterCode:'from multiprocessing import current_process\nprint(current_process().name)',expectedOutput:'MainProcess',hints:['The current process is enough for this browser-friendly concept exercise.','Process state is separate from thread-local state.'],challenge:c('MainProcess',undefined,[/multiprocessing/]) },
{ id:'l9_locks',layer:9,topic:'locks',title:'GUARD THE SHARED STATE.',brief:'Use a lock to protect a critical section.',explanation:'A lock lets one participant at a time enter a protected region. Correctness still depends on how the critical section is designed.',roast:'Because “it probably won’t race” is not a synchronization strategy.',difficulty:'ADVANCED',minutes:26,starterCode:'import threading\nlock = threading.Lock()\nvalue = 0\nwith lock:\n    value += 1\nprint(value)',expectedOutput:'1',hints:['Acquire through with lock.','Mutate the shared value inside the protected block.'],challenge:c('1',undefined,[/threading\.Lock/,/with\s+lock/]) },
{ id:'l9_race',layer:9,topic:'race conditions',title:'CHASE THE RACE.',brief:'Recognize why unsynchronized shared state is dangerous.',explanation:'A race condition occurs when correctness depends on timing or interleaving between concurrent operations.',roast:'The program works 99 times, therefore you ship it Friday.',difficulty:'ADVANCED',minutes:24,starterCode:'print("Shared mutable state needs a synchronization strategy")',expectedOutput:'Shared mutable state needs a synchronization strategy',hints:['The bug class is about interleavings.','Ask what can happen between read and write operations.'],challenge:c('Shared mutable state needs a synchronization strategy') },
{ id:'l9_async',layer:9,topic:'async/await',title:'AWAIT THE HYDRA.',brief:'Suspend a coroutine while another operation completes.',explanation:'async def creates a coroutine function; await suspends the coroutine until the awaited operation completes.',roast:'Cooperative multitasking. Everyone promises not to block. Nobody trusts anyone.',difficulty:'ADVANCED',minutes:26,starterCode:'import asyncio\nasync def main():\n    await asyncio.sleep(0)\n    print("scheduled")\nasyncio.run(main())',expectedOutput:'scheduled',hints:['Use async def.','await the sleep before printing.'],challenge:c('scheduled',undefined,[/async\s+def/,/\bawait\b/,/asyncio\.run/]) },
{ id:'l9_asyncio',layer:9,topic:'asyncio',title:'SCHEDULE THE CROWD.',brief:'Schedule coroutines and collect their results.',explanation:'asyncio provides an event loop and coroutine scheduling primitives for cooperative concurrency.',roast:'Your callbacks are now a traffic system.',difficulty:'ADVANCED',minutes:28,starterCode:'import asyncio\n\nasync def one(): return 1\nasync def two(): return 2\n\nasync def main():\n    print(await asyncio.gather(one(), two()))\n\nasyncio.run(main())',expectedOutput:'[1, 2]',hints:['Use asyncio.gather.','Await the gathered result.'],challenge:c('[1, 2]',undefined,[/asyncio\.gather/,/await/]) },

{ id:'l10_identity',layer:10,topic:'identity',title:'MEET THE MEMORY REAPER.',brief:'Separate equality from object identity.',explanation:'== asks whether values compare equal. is tests object identity. Use identity deliberately.',roast:'Same contents. Different object. The Reaper smiles.',difficulty:'ADVANCED',minutes:18,starterCode:'a = [1, 2]\nb = [1, 2]\nprint(a == b)\nprint(a is b)',expectedOutput:'True\nFalse',hints:['The lists compare equal by contents.','They are separate list objects.'],challenge:c('True\nFalse',undefined,[/==/,/\bis\b/]) },
{ id:'l10_references',layer:10,topic:'references',title:'FOLLOW THE REFERENCE.',brief:'Understand aliasing without pretending variables are boxes.',explanation:'Two names can reference the same object. Mutations through either name affect the shared object.',roast:'Two names. One object. Zero privacy.',difficulty:'ADVANCED',minutes:20,starterCode:'a = []\nb = a\nb.append("fire")\nprint(a)',expectedOutput:"['fire']",hints:['Bind b to a.','Mutate through b.'],challenge:c("['fire']",undefined,[/b\s*=\s*a/,/b\.append/]) },
{ id:'l10_refcount',layer:10,topic:'reference counting',title:'COUNT THE REFERENCES.',brief:'Separate Python semantics from CPython reference counting.',explanation:'CPython uses reference counting as part of its memory management. This is an implementation detail, not a universal Python language rule.',roast:'Implementation details are where easy explanations go to die.',difficulty:'ADVANCED',minutes:26,starterCode:'print("CPython-specific: reference counting is an implementation detail")',expectedOutput:'CPython-specific: reference counting is an implementation detail',hints:['Do not describe CPython behavior as Python language law.','Version-label implementation details.'],challenge:c('CPython-specific: reference counting is an implementation detail') },
{ id:'l10_gc',layer:10,topic:'garbage collection',title:'CALL THE COLLECTOR.',brief:'Understand cyclic garbage collection.',explanation:'CPython supplements reference counting with a cyclic garbage collector so some reference cycles can be reclaimed.',roast:'Reference counting alone meets its final boss: cycles.',difficulty:'ADVANCED',minutes:28,starterCode:'import gc\nprint(callable(gc.collect))',expectedOutput:'True',hints:['The gc module exposes collection tools in CPython.','The exact collector behavior is implementation-specific.'],challenge:c('True',undefined,[/import\s+gc/,/gc\.collect/]) },
{ id:'l10_object_lifetime',layer:10,topic:'object lifetime',title:'WHEN DOES THE OBJECT DIE?',brief:'Reason about reachability and lifetime.',explanation:'An object remains usable while references keep it reachable. Exact destruction timing can be implementation-dependent.',roast:'Never promise a destructor date you cannot prove.',difficulty:'ADVANCED',minutes:24,starterCode:'obj = {"alive": True}\nref = obj\ndel obj\nprint(ref["alive"])',expectedOutput:'True',hints:['ref keeps the object reachable.','del removes one binding, not necessarily the object.'],challenge:c('True',undefined,[/del\s+obj/,/ref\s*=\s*obj/]) },
{ id:'l10_allocation',layer:10,topic:'allocation',title:'ALLOCATE WITHOUT HAND-WAVING.',brief:'Understand that objects require runtime storage.',explanation:'Creating objects involves allocation and initialization. The exact allocator and memory layout are implementation details.',roast:'Memory is not “somewhere over there”. The runtime has a plan.',difficulty:'ADVANCED',minutes:24,starterCode:'value = []\nprint(type(value).__name__)',expectedOutput:'list',hints:['Keep the lesson at the language level first.','Do not invent a universal memory address story.'],challenge:c('list',undefined,[/\[\]/]) },
{ id:'l10_memory_behavior',layer:10,topic:'memory behavior',title:'MEASURE, THEN CLAIM.',brief:'Treat memory observations as evidence, not mythology.',explanation:'Memory behavior depends on the implementation, workload, allocator, and platform. Measurements need context.',roast:'Your benchmark is not a law of nature.',difficulty:'ADVANCED',minutes:26,starterCode:'import sys\nprint(sys.implementation.name)',expectedOutput:'cpython',hints:['Observe the implementation explicitly.','Avoid claiming the result generalizes to every Python implementation.'],challenge:c('cpython',undefined,[/sys\.implementation/]) },

{ id:'l11_bytecode',layer:11,topic:'bytecode',title:'DISASSEMBLE THE SPELL.',brief:'Inspect a function as CPython bytecode.',explanation:'Bytecode is an implementation detail of CPython and can change across versions.',roast:'Welcome below the language level. Bring documentation.',difficulty:'ADVANCED',minutes:25,starterCode:'import dis\ndef add(a, b):\n    return a + b\n\ndis.dis(add)',expectedOutput:'',hints:['Use the dis module.','Do not hard-code opcode names as universal truths.'],challenge:c('', 'dis.dis(add)',[/import\s+dis/,/def\s+add/]) },
{ id:'l11_pythobject',layer:11,topic:'PyObject',title:'OBJECTS UNDER THE FLOORBOARDS.',brief:'Learn what PyObject means in CPython.',explanation:'PyObject is a CPython C-level object representation concept. Object layout is implementation-specific.',roast:'Everything is an object — now prove what you mean.',difficulty:'ADVANCED',minutes:28,starterCode:'print("PyObject is a CPython implementation concept")',expectedOutput:'PyObject is a CPython implementation concept',hints:['Separate language concepts from C-level implementation structures.','Version-label internals.'],challenge:c('PyObject is a CPython implementation concept') },
{ id:'l11_interpreter',layer:11,topic:'interpreter execution',title:'DESCEND INTO THE INTERPRETER.',brief:'Connect source code, code objects, and interpreter execution.',explanation:'Python source is compiled to code objects; CPython executes that compiled representation using its interpreter machinery.',roast:'You have reached the engine room. Please touch nothing.',difficulty:'ADVANCED',minutes:30,starterCode:'code = compile("x = 1", "<demo>", "exec")\nprint(type(code).__name__)\nprint(code.co_filename)',expectedOutput:'code\n<demo>',hints:['compile() returns a code object.','co_filename is part of the code object metadata.'],challenge:c('code\n<demo>',undefined,[/compile\s*\(/,/co_filename/]) },
{ id:'l11_disassembly',layer:11,topic:'dis',title:'INSPECT WITHOUT GUESSING.',brief:'Use disassembly as evidence about one specific CPython build.',explanation:'The dis module exposes bytecode analysis. Exact instruction sequences are version-sensitive.',roast:'One build, one observation. No universal opcode prophecy.',difficulty:'ADVANCED',minutes:28,starterCode:'import dis\ncode = compile("x = 1", "<demo>", "exec")\nprint(any(i.opname for i in dis.get_instructions(code)))',expectedOutput:'True',hints:['Compile the code first.','Inspect it with dis.get_instructions.'],challenge:c('True',undefined,[/dis\.get_instructions/]) },
{ id:'l11_gdb',layer:11,topic:'GDB',title:'TRACE THE MACHINE.',brief:'Understand what debugger-level inspection can reveal.',explanation:'GDB can inspect native CPython processes and C-level state. This is outside browser execution and should be treated as a native-development workflow.',roast:'The browser cannot save you here. Welcome to native land.',difficulty:'ADVANCED',minutes:30,starterCode:'print("Native GDB inspection belongs to a local CPython build")',expectedOutput:'Native GDB inspection belongs to a local CPython build',hints:['This is a workflow lesson, not a browser debugger.','Separate conceptual knowledge from tool access.'],challenge:c('Native GDB inspection belongs to a local CPython build') },
{ id:'l11_c_extensions',layer:11,topic:'C extensions',title:'CROSS THE C API.',brief:'Understand why native extensions care about the interpreter ABI and runtime.',explanation:'CPython exposes a C API for extension modules. Compatibility and interpreter details matter when writing native code.',roast:'Python stops protecting you at the C boundary.',difficulty:'ADVANCED',minutes:30,starterCode:'print("CPython extensions use the C API")',expectedOutput:'CPython extensions use the C API',hints:['Think about ABI/API boundaries.','Implementation details can vary by version.'],challenge:c('CPython extensions use the C API') },

{ id:'l12_free_threading',layer:12,topic:'free-threading',title:'TURN OFF THE GIL — CAREFULLY.',brief:'Understand CPython free-threaded builds.',explanation:'Starting with CPython 3.13, free-threaded builds can run with the GIL disabled. This is a build/runtime configuration and not a claim about every Python build.',roast:'The GIL is optional here. Your certainty should not be.',difficulty:'ADVANCED',minutes:30,starterCode:'print("CPython 3.13 free-threading is experimental")\nprint("Verify the build before making concurrency claims")',expectedOutput:'CPython 3.13 free-threading is experimental\nVerify the build before making concurrency claims',hints:['Label this as CPython-specific.','Do not imply the normal build is automatically free-threaded.'],challenge:c('CPython 3.13 free-threading is experimental\nVerify the build before making concurrency claims') },
{ id:'l12_subinterpreters',layer:12,topic:'subinterpreters',title:'SPLIT THE RUNTIME.',brief:'Understand multiple interpreter states as a CPython concept.',explanation:'CPython can host multiple interpreter states within a process. Exact isolation and concurrency behavior are implementation details.',roast:'One process. More than one interpreter. More than one way to regret a design.',difficulty:'ADVANCED',minutes:30,starterCode:'print("CPython can host multiple interpreter states")',expectedOutput:'CPython can host multiple interpreter states',hints:['Think runtime state, not just threads.','Keep implementation claims version-labelled.'],challenge:c('CPython can host multiple interpreter states') },
{ id:'l12_jit',layer:12,topic:'JIT',title:'THE EXPERIMENTAL JIT.',brief:'Know when the experimental CPython JIT is present.',explanation:'CPython 3.13 introduced an experimental JIT build configuration. Availability depends on how CPython was built and used.',roast:'No, Python did not become JavaScript overnight.',difficulty:'ADVANCED',minutes:30,starterCode:'print("CPython JIT availability is build-dependent")\nprint("Experimental does not mean enabled everywhere")',expectedOutput:'CPython JIT availability is build-dependent\nExperimental does not mean enabled everywhere',hints:['Verify the build configuration.','Do not treat experimental features as universal defaults.'],challenge:c('CPython JIT availability is build-dependent\nExperimental does not mean enabled everywhere') },
{ id:'l12_performance',layer:12,topic:'performance',title:'BENCHMARK THE DEMON.',brief:'Measure before optimizing.',explanation:'Performance work should use a representative workload and a measurement method. Interpreter, platform, and build all affect results.',roast:'Your intuition has filed a bug report against your benchmark.',difficulty:'ADVANCED',minutes:26,starterCode:'import timeit\nprint(timeit.timeit("sum(range(10))", number=100))',expectedOutput:'',hints:['Use timeit for repeatable small measurements.','Do not compare single noisy timings as facts.'],challenge:c('',undefined,[/timeit\.timeit/]) },
];
