export type Lesson = { id:string; layer:number; topic:string; title:string; brief:string; explanation:string; roast:string; difficulty:'BEGINNER'|'INTERMEDIATE'|'ADVANCED'; minutes:number; starterCode:string; expectedOutput:string; hints:string[] };
export const lessonCatalog: Lesson[] = [
{id:'l1_print',layer:1,topic:'print()',title:'SPEAK, MORTAL.',brief:'Teach the machine its first word. Then make it say something useful.',explanation:'print() sends a value to standard output. Strings are text values, usually written inside quotes. Comments begin with # and are ignored by Python.',roast:'You have discovered the print function. Humanity may now communicate with machines. Please do not put this on your résumé.',difficulty:'BEGINNER',minutes:8,starterCode:'# Your first spell\nprint("hello, hell")',expectedOutput:'hello, hell',hints:['Call print() with a string.','The exact text must be hello, hell.']},
{id:'l1_variables',layer:1,topic:'variables',title:'NAME THE DEMON.',brief:'Store a value in a variable, then summon it later.',explanation:'A variable name refers to an object. Assignment binds the name to a value; it does not mean the name contains a tiny box of bytes.',roast:'Congratulations. You invented a label. Try not to name everything temp_final_final2.',difficulty:'BEGINNER',minutes:10,starterCode:'name = "Pythonsura"\nprint(name)',expectedOutput:'Pythonsura',hints:['Create a variable called name.','Store the string Pythonsura in it.']},
{id:'l1_numbers',layer:1,topic:'numbers',title:'COUNT THE DAMAGE.',brief:'Use numbers and arithmetic without summoning a traceback.',explanation:'Python integers have arbitrary precision in normal Python semantics. Arithmetic expressions evaluate to values you can store, print, and combine.',roast:'At last: mathematics without a spreadsheet. Mostly.',difficulty:'BEGINNER',minutes:10,starterCode:'damage = 7\nbonus = 5\nprint(damage + bonus)',expectedOutput:'12',hints:['Add the two variables.','Print the result of damage + bonus.']},
{id:'l1_input',layer:1,topic:'input()',title:'ASK THE MORTAL.',brief:'Read text from the user and respond.',explanation:'input() reads a line and returns a string. Convert it explicitly when you need a number.',roast:'The computer is finally asking YOU a question. This will end well.',difficulty:'BEGINNER',minutes:12,starterCode:'name = "heretic"\nprint("Welcome", name)',expectedOutput:'Welcome heretic',hints:['Use print with two values.','The expected output has one space between Welcome and heretic.']},
{id:'l2_if',layer:2,topic:'if',title:'CHOOSE YOUR FATE.',brief:'Make a decision before the branch makes one for you.',explanation:'if statements execute a suite only when their condition is truthy. elif and else provide alternative paths.',roast:'Control flow: because apparently straight lines were too peaceful.',difficulty:'BEGINNER',minutes:12,starterCode:'hp = 10\nif hp > 0:\n    print("alive")',expectedOutput:'alive',hints:['The condition should test whether hp is above zero.','Indent the print statement under if.']},
{id:'l3_for',layer:3,topic:'for',title:'ITERATE OR PERISH.',brief:'Repeat a task without copying and pasting it like a mortal.',explanation:'A for loop iterates over an iterable, assigning each item to the loop target in turn.',roast:'Copy-paste is not a loop. It is a cry for help.',difficulty:'BEGINNER',minutes:12,starterCode:'for i in range(3):\n    print(i)',expectedOutput:'0\n1\n2',hints:['range(3) produces 0, 1, 2.','Print the loop variable.']},
];
