export type ProjectMilestone={id:string;title:string;objective:string;acceptance:string[]};
export type Project={id:string;tier:'beginner'|'intermediate'|'advanced';title:string;name:string;difficulty:'BEGINNER'|'INTERMEDIATE'|'ADVANCED';brief:string;firstTask:string;skills:string[];milestones:ProjectMilestone[];rewardXp:number};
export const projects:Project[]=[
{id:'calculator',tier:'beginner',title:'HELL CALCULATOR',name:'HELL CALCULATOR',difficulty:'BEGINNER',brief:'Build a CLI calculator with explicit validation and error handling.',firstTask:'Accept two numbers and an operator before writing the calculation branch.',skills:['input','type conversion','conditions','functions'],milestones:[{id:'c1',title:'Parse input',objective:'Accept two numbers and an operator.',acceptance:['supports + - * /']},{id:'c2',title:'Handle failure',objective:'Reject invalid operators and division by zero.',acceptance:['clear error message','program remains usable']},{id:'c3',title:'Extract logic',objective:'Move calculation into a reusable function.',acceptance:['function returns the result']}],rewardXp:150},
{id:'quiz',tier:'beginner',title:'INFERNAL QUIZ',name:'INFERNAL QUIZ',difficulty:'BEGINNER',brief:'Create a quiz engine with scoring, validation and replay.',firstTask:'Define one question as data before writing the quiz loop.',skills:['lists','dicts','loops','functions'],milestones:[{id:'q1',title:'Question model',objective:'Represent questions and answers consistently.',acceptance:['multiple questions work']},{id:'q2',title:'Score answers',objective:'Compare answers and update a score.',acceptance:['correct answers increment score']},{id:'q3',title:'Replay loop',objective:'Allow another round without restarting the program.',acceptance:['state resets correctly']}],rewardXp:180},
{id:'expense-tracker',tier:'intermediate',title:'SOUL EXPENSE TRACKER',name:'SOUL EXPENSE TRACKER',difficulty:'INTERMEDIATE',brief:'Model expenses, summarize categories, and detect malformed entries.',firstTask:'Represent one valid record and three invalid examples.',skills:['collections','functions','validation','data processing'],milestones:[{id:'e1',title:'Model records',objective:'Represent one expense consistently.',acceptance:['amount and category are available']},{id:'e2',title:'Aggregate',objective:'Compute totals by category.',acceptance:['missing categories do not crash the report']},{id:'e3',title:'Validate',objective:'Reject malformed expense data.',acceptance:['errors identify the bad field']}],rewardXp:250},
{id:'log-analyzer',tier:'intermediate',title:'LOG ABYSS ANALYZER',name:'LOG ABYSS ANALYZER',difficulty:'INTERMEDIATE',brief:'Parse log lines and summarize recurring error classes.',firstTask:'Define the log grammar before implementing the parser.',skills:['strings','dicts','exceptions','data processing'],milestones:[{id:'l1',title:'Parse records',objective:'Extract level and message from input lines.',acceptance:['well-formed lines parse deterministically']},{id:'l2',title:'Aggregate',objective:'Count events by level.',acceptance:['counts are stable']},{id:'l3',title:'Report',objective:'Produce a concise summary.',acceptance:['unknown lines are reported clearly']}],rewardXp:300},
{id:'traceback-forensics',tier:'advanced',title:'TRACEBACK FORENSICS',name:'TRACEBACK FORENSICS',difficulty:'ADVANCED',brief:'Build a debugging utility that captures failures and groups them by exception type.',firstTask:'Create a tiny corpus of representative failures before implementing analysis.',skills:['exceptions','tracebacks','logging','analysis'],milestones:[{id:'t1',title:'Capture failure',objective:'Record exception type and message.',acceptance:['exception details are preserved']},{id:'t2',title:'Summarize',objective:'Group failures by exception type.',acceptance:['counts are deterministic']},{id:'t3',title:'Explain',objective:'Produce remediation hints for known error classes.',acceptance:['unknown errors remain clearly unknown']}],rewardXp:400},
{id:'runtime-inspector',tier:'advanced',title:'RUNTIME INSPECTOR',name:'RUNTIME INSPECTOR',difficulty:'ADVANCED',brief:'Explore bytecode and code-object metadata for a target CPython runtime.',firstTask:'Record the exact interpreter version before making any runtime claim.',skills:['dis','code objects','introspection','version labelling'],milestones:[{id:'r1',title:'Inspect code',objective:'Compile a small function and inspect its code object.',acceptance:['co_filename and co_name are shown']},{id:'r2',title:'Disassemble',objective:'Use dis without assuming opcode stability.',acceptance:['instructions are displayed']},{id:'r3',title:'Explain',objective:'Label observations as CPython-specific and version-sensitive.',acceptance:['claims include target version']}],rewardXp:500},
];
