type CtxWithWebkit=Window & typeof globalThis & {webkitAudioContext?:typeof AudioContext};

export class HellAudio {
 private ctx?:AudioContext;
 private master?:GainNode;
 private ambience?:{drone:OscillatorNode;droneGain:GainNode;wind:AudioBufferSourceNode;windGain:GainNode};
 private ensure(){if(this.ctx&&this.ctx.state!=='closed')return this.ctx;const Ctx=window.AudioContext??(window as CtxWithWebkit).webkitAudioContext;if(!Ctx)return undefined;const ctx=new Ctx();const master=ctx.createGain();master.gain.value=.18;master.connect(ctx.destination);this.ctx=ctx;this.master=master;return ctx}
 private env(duration:number=0.6,peak=.2){const ctx=this.ensure();if(!ctx||!this.master)return undefined;const gain=ctx.createGain();gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(peak,ctx.currentTime+.025);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);gain.connect(this.master);return gain}
 startAmbience(){const ctx=this.ensure();if(!ctx||!this.master||this.ambience)return;void ctx.resume();const drone=ctx.createOscillator();drone.type='sine';drone.frequency.value=38;const droneGain=ctx.createGain();droneGain.gain.value=.05;drone.connect(droneGain).connect(this.master);drone.start();const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.22;const wind=ctx.createBufferSource();wind.buffer=buffer;wind.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=520;const windGain=ctx.createGain();windGain.gain.value=.018;wind.connect(filter).connect(windGain).connect(this.master);wind.start();this.ambience={drone,droneGain,wind,windGain}}
 setMuted(muted:boolean){if(this.master)this.master.gain.value=muted?0:.18}
 rumble(){const ctx=this.ensure();const gain=this.env(.95,.32);if(!ctx||!gain)return;const osc=ctx.createOscillator();osc.type='sine';osc.frequency.setValueAtTime(52,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(24,ctx.currentTime+.9);osc.connect(gain);osc.start();osc.stop(ctx.currentTime+1)}
 quake(){const ctx=this.ensure();if(!ctx||!this.master)return;const gain=this.env(.22,.26);if(!gain)return;const osc=ctx.createOscillator();osc.type='sawtooth';osc.frequency.setValueAtTime(110,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(32,ctx.currentTime+.18);osc.connect(gain);osc.start();osc.stop(ctx.currentTime+.23);this.noise(.16,.18,700)}
 roar(){const ctx=this.ensure();if(!ctx||!this.master)return;const gain=this.env(1.6,.22);if(!gain)return;const osc=ctx.createOscillator();osc.type='sawtooth';osc.frequency.setValueAtTime(92,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(42,ctx.currentTime+1.4);const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=420;osc.connect(filter).connect(gain);osc.start();osc.stop(ctx.currentTime+1.6);this.noise(1.3,.14,900)}
 portal(){const ctx=this.ensure();if(!ctx)return;const gain=this.env(1.1,.16);if(!gain)return;const osc=ctx.createOscillator();osc.type='triangle';osc.frequency.setValueAtTime(90,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(980,ctx.currentTime+1.0);osc.connect(gain);osc.start();osc.stop(ctx.currentTime+1.15);this.noise(.9,.05,1600)}
 spark(){const ctx=this.ensure();const gain=this.env(.12,.07);if(!ctx||!gain)return;const osc=ctx.createOscillator();osc.type='square';osc.frequency.value=1650;osc.connect(gain);osc.start();osc.stop(ctx.currentTime+.1)}
 impact(){const ctx=this.ensure();if(!ctx)return;const gain=this.env(.4,.3);if(!gain)return;const osc=ctx.createOscillator();osc.type='square';osc.frequency.setValueAtTime(150,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(42,ctx.currentTime+.35);osc.connect(gain);osc.start();osc.stop(ctx.currentTime+.42);this.noise(.32,.24,900)}
 chain(){const ctx=this.ensure();const gain=this.env(.5,.055);if(!ctx||!gain)return;const osc=ctx.createOscillator();osc.type='triangle';osc.frequency.value=640;osc.connect(gain);osc.start();osc.stop(ctx.currentTime+.12);window.setTimeout(()=>{const g=this.env(.38,.04);if(!g)return;const o=ctx.createOscillator();o.type='triangle';o.frequency.value=410;o.connect(g);o.start();o.stop(ctx.currentTime+.08)},90)}
 footstep(){const ctx=this.ensure();if(!ctx)return;this.noise(.09,.09,240)}
 laugh(){const ctx=this.ensure();const gain=this.env(.75,.1);if(!ctx||!gain)return;const o=ctx.createOscillator();o.type='sawtooth';o.frequency.setValueAtTime(240,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(520,ctx.currentTime+.18);o.frequency.exponentialRampToValueAtTime(190,ctx.currentTime+.42);o.connect(gain);o.start();o.stop(ctx.currentTime+.5)}
 private noise(duration:number,peak:number,filterHz:number){const ctx=this.ensure();if(!ctx||!this.master)return;const buffer=ctx.createBuffer(1,Math.max(1,Math.floor(ctx.sampleRate*duration)),ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(.75-(i/data.length)*.5);const src=ctx.createBufferSource();src.buffer=buffer;const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=filterHz;const gain=ctx.createGain();gain.gain.value=peak;src.connect(filter).connect(gain).connect(this.master);src.start();src.stop(ctx.currentTime+duration+.03)}
 dispose(){try{this.ambience?.drone.stop();this.ambience?.wind.stop()}catch{};this.ambience=undefined;if(this.ctx){void this.ctx.close();this.ctx=undefined};this.master=undefined}
}

export const hellAudio=new HellAudio();
