import type {Progress,AttemptStats} from '../types/progress';
import {updateStreak} from './streaks';
const KEY='python-from-hell:rpg-progress:v2';
const blankAttempt=():AttemptStats=>({attempts:0,successes:0,failures:0,hintsUsed:0,totalMs:0,lastOutcome:null,mastery:0});
export function createInitialProgress():Progress{return{version:2,currentLayer:1,currentLessonId:'l1_print',completedLessons:[],xp:0,streak:0,longestStreak:0,lastActiveDate:null,mastery:{},attempts:{},achievements:[],unlockedBosses:['loop-demon'],completedBosses:[],projectRewards:[],projects:{},interview:{round:0,score:0,rank:'UNRANKED'},settings:{roastIntensity:'SAVAGE',sound:false,reducedMotion:false}}}
function migrate(raw:unknown):Progress|null{if(!raw||typeof raw!=='object')return null;const p=raw as Partial<Progress>&{version?:number;mastery?:Record<string,number>};if(p.version===2&&Array.isArray(p.completedLessons)&&typeof p.xp==='number')return{...createInitialProgress(),...p,settings:{...createInitialProgress().settings,...p.settings},attempts:p.attempts??{},projectRewards:p.projectRewards??[]};if(p.version===1&&Array.isArray(p.completedLessons)&&typeof p.xp==='number'){const attempts:Record<string,AttemptStats>={};for(const[id,mastery]of Object.entries(p.mastery??{}))attempts[id]={...blankAttempt(),mastery:Math.max(0,Math.min(1,(Number(mastery)||0)/100))};return{...createInitialProgress(),currentLayer:p.currentLayer??1,currentLessonId:p.currentLessonId??'l1_print',completedLessons:p.completedLessons,xp:p.xp,streak:p.streak??0,mastery:p.mastery??{},attempts};}return null}
export function loadProgress():Progress|null{try{const raw=localStorage.getItem(KEY)??localStorage.getItem('python-from-hell:rpg-progress:v1');if(!raw)return null;return migrate(JSON.parse(raw))}catch{return null}}
export function saveProgress(p:Progress){try{localStorage.setItem(KEY,JSON.stringify(p))}catch{}}
export function awardXp(p:Progress,amount:number):Progress{return{...updateStreak(p),xp:Math.max(0,p.xp+Math.max(0,amount))}}
export function recordAttempt(p:Progress,lessonId:string,success:boolean,hintUsed=false,elapsedMs=0):Progress{const old=p.attempts[lessonId]??blankAttempt();const attempts=old.attempts+1;const successes=old.successes+(success?1:0);const failures=old.failures+(success?0:1);const mastery=Math.max(0,Math.min(100,(old.mastery*.7)+(success?30:-12)+(hintUsed?-5:0)));const next={...old,attempts,successes,failures,hintsUsed:old.hintsUsed+(hintUsed?1:0),totalMs:old.totalMs+Math.max(0,elapsedMs),lastOutcome:success?'success':'failure',mastery:Math.round(mastery*10)/10};return{...updateStreak(p),attempts:{...p.attempts,[lessonId]:next},mastery:{...p.mastery,[lessonId]:next.mastery}}}
export function completeLesson(p:Progress,id:string):Progress{if(p.completedLessons.includes(id))return p;return{...updateStreak(p),currentLessonId:id,completedLessons:[...p.completedLessons,id],mastery:{...p.mastery,[id]:100},attempts:{...p.attempts,[id]:{...(p.attempts[id]??blankAttempt()),mastery:100,lastOutcome:'success'}}}}
