export type RunResult={stdout:string;stderr:string;error?:string;cancelled?:boolean;timedOut?:boolean};
type Pending={id:number;resolve:(result:RunResult)=>void};
export class PythonRunner {
 private worker?:Worker;private timer?:number;private id=0;private pending?:Pending;
 private createWorker(){const worker=new Worker(new URL('./python.worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>{const pending=this.pending;if(!pending||pending.id!==this.id)return;this.pending=undefined;if(this.timer)window.clearTimeout(this.timer);this.timer=undefined;pending.resolve(e.data as RunResult)};worker.onerror=e=>{const pending=this.pending;this.pending=undefined;if(this.timer)window.clearTimeout(this.timer);this.timer=undefined;this.worker=undefined;worker.terminate();pending?.resolve({stdout:'',stderr:'',error:e.message||'Python worker failed'})};this.worker=worker;return worker}
 private ensureWorker(){return this.worker??this.createWorker()}
 run(code:string):Promise<RunResult>{this.stop('Previous execution cancelled.');const id=++this.id;return new Promise(resolve=>{this.pending={id,resolve};const worker=this.ensureWorker();try{worker.postMessage({code})}catch(error){this.pending=undefined;worker.terminate();this.worker=undefined;resolve({stdout:'',stderr:'',error:error instanceof Error?error.message:'Unable to start Python execution'});return}this.timer=window.setTimeout(()=>{const pending=this.pending;if(!pending||pending.id!==id)return;this.pending=undefined;this.timer=undefined;this.worker?.terminate();this.worker=undefined;pending.resolve({stdout:'',stderr:'',error:'Execution timed out after 5 seconds.',timedOut:true})},5000)})}
 stop(message='Execution stopped by user.'){this.id++;const pending=this.pending;this.pending=undefined;if(this.timer)window.clearTimeout(this.timer);this.timer=undefined;this.worker?.terminate();this.worker=undefined;pending?.resolve({stdout:'',stderr:'',error:message,cancelled:true})}
 dispose(){this.stop('Execution disposed.');}
}
