import {useEffect,useMemo,useState,type Dispatch,type SetStateAction} from 'react';
import {Play,RotateCcw,Sparkles,ChevronRight,ShieldCheck,Square} from 'lucide-react';
import {lessonCatalog} from '../domain/lessons';
import type {Lesson} from '../domain/lessons';
import type {Progress} from '../types/progress';
import {evaluateLessonChallenge} from '../engine/challengeRunner';
import {PythonRunner} from '../execution/PythonRunner';
import {claimLessonReward,completeLesson,recordAttempt} from '../engine/progress';
import {XP_REWARDS} from '../engine/xp';
import {recommendedHintIndex,type MasteryRecord} from '../engine/adaptive';
import {playSfx} from '../engine/audio';
import {TutorGuide} from './TutorGuide';

type Props={lesson:Lesson;progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>;onBack:()=>void;onNextLesson:(id:string)=>void};
const DRAFTS_KEY='python-from-hell:lesson-drafts:v1';
function adaptiveMap(progress:Progress):Record<string,MasteryRecord>{return Object.fromEntries(Object.entries(progress.attempts).map(([id,a])=>[id,{...a,mastery:Math.max(0,Math.min(1,a.mastery/100))}]));}
function loadDraft(id:string,starter:string){try{const drafts=JSON.parse(localStorage.getItem(DRAFTS_KEY)||'{}') as Record<string,unknown>;return typeof drafts[id]==='string'?drafts[id] as string:starter}catch{return starter}}
function saveDraft(id:string,code:string){try{const drafts=JSON.parse(localStorage.getItem(DRAFTS_KEY)||'{}') as Record<string,unknown>;drafts[id]=code;localStorage.setItem(DRAFTS_KEY,JSON.stringify(drafts))}catch{}}
function clearDraft(id:string){try{const drafts=JSON.parse(localStorage.getItem(DRAFTS_KEY)||'{}') as Record<string,unknown>;delete drafts[id];localStorage.setItem(DRAFTS_KEY,JSON.stringify(drafts))}catch{}}
export function LessonWorkspace({lesson,progress,setProgress,onBack,onNextLesson}:Props){
 const stats=progress.attempts[lesson.id];const adaptiveRecord=stats?{attempts:stats.attempts,successes:stats.successes,failures:stats.failures,hintsUsed:stats.hintsUsed,totalMs:stats.totalMs,lastOutcome:stats.lastOutcome,mastery:Math.max(0,Math.min(1,stats.mastery/100))}:{attempts:0,successes:0,failures:0,hintsUsed:0,totalMs:0,lastOutcome:null,mastery:0};const suggestedHint=stats?recommendedHintIndex(adaptiveRecord,lesson.hints.length):0;
 const [code,setCode]=useState(()=>loadDraft(lesson.id,lesson.starterCode));const [output,setOutput]=useState('Runtime standing by.');const [running,setRunning]=useState(false);const [hint,setHint]=useState(suggestedHint);const [startedAt,setStartedAt]=useState(()=>Date.now());const [message,setMessage]=useState('');const [privateChecked,setPrivateChecked]=useState(false);const runner=useMemo(()=>new PythonRunner(),[]);
 useEffect(()=>()=>runner.dispose(),[runner]);useEffect(()=>{setCode(loadDraft(lesson.id,lesson.starterCode));setOutput('Runtime standing by.');setHint(recommendedHintIndex(stats?{attempts:stats.attempts,successes:stats.successes,failures:stats.failures,hintsUsed:stats.hintsUsed,totalMs:stats.totalMs,lastOutcome:stats.lastOutcome,mastery:Math.max(0,Math.min(1,stats.mastery/100))}:{attempts:0,successes:0,failures:0,hintsUsed:0,totalMs:0,lastOutcome:null,mastery:0},lesson.hints.length));setMessage('');setPrivateChecked(false);setStartedAt(Date.now())},[lesson.id,lesson.starterCode,lesson.hints.length]);
 useEffect(()=>{setHint(current=>Math.max(current,suggestedHint))},[suggestedHint]);
 const done=progress.completedLessons.includes(lesson.id);
 const updateCode=(value:string)=>{setCode(value);saveDraft(lesson.id,value)};
 const run=async()=>{if(running||done)return;setRunning(true);setMessage('');setPrivateChecked(false);setOutput('Executing in isolated Python runtime…');const result=await runner.run(code);if(result.cancelled){setRunning(false);setMessage('Execution cancelled. No attempt was recorded.');setStartedAt(Date.now());return}const elapsed=Date.now()-startedAt;const judged=await evaluateLessonChallenge(lesson,code,result,runner);const success=judged.passed;const outcome=result.timedOut?'timeout':success?'success':result.error?'runtime-error':'failure';const hintUsed=hint>0;const tracked=recordAttempt(progress,lesson.id,success,hintUsed,elapsed,outcome);const record=tracked.attempts[lesson.id];const mastered=success&&record.successes>=3&&record.mastery>=82;const reason=result.error?`ERROR: ${result.error}`:judged.reason;setOutput(result.error?`ERROR\n${result.error}`:result.stderr?`${result.stdout?result.stdout+'\n':''}${result.stderr}`:result.stdout||'(no output)');setPrivateChecked(Boolean(judged.hiddenChecked));if(progress.settings.sound)playSfx(outcome!=='success'?'fail':mastered?'success':'enter');setProgress(p=>{if(!success||!mastered)return recordAttempt(p,lesson.id,success,hintUsed,elapsed,outcome);const completed=completeLesson(record?{...p,attempts:{...p.attempts,[lesson.id]:record},mastery:{...p.mastery,[lesson.id]:record.mastery}}:p,lesson.id);const cleanXp=hintUsed?0:XP_REWARDS.noHint;return claimLessonReward(completed,lesson.id,XP_REWARDS.lesson+XP_REWARDS.challenge+cleanXp,!hintUsed)});setMessage(mastered?`CONCEPT MASTERED — ${judged.reason}`:success?`PASS — ${judged.reason} Mastery is ${Math.round(record?.mastery??0)}%. I am making you prove it again.`:`${reason} Attempt ${tracked.attempts[lesson.id]?.attempts??0} recorded.`);setRunning(false);setStartedAt(Date.now())};
 const stop=()=>{if(!running)return;runner.stop();setOutput('ERROR\nExecution stopped by user.');setMessage('Execution cancelled. No attempt was recorded.');setRunning(false);setStartedAt(Date.now())};
 const reveal=()=>setHint(Math.min(hint+1,Math.max(0,lesson.hints.length-1)));const reset=()=>{clearDraft(lesson.id);setCode(lesson.starterCode);setOutput('Runtime standing by.');setMessage('Draft cleared. Starter code restored.');setPrivateChecked(false);setStartedAt(Date.now())};
 const index=lessonCatalog.findIndex(item=>item.id===lesson.id);const nextLesson=index>=0?lessonCatalog[index+1]:undefined;const advance=()=>nextLesson?onNextLesson(nextLesson.id):onBack();
 return <div className="page lesson-page"><div className="lesson-head"><button className="back-btn" onClick={onBack}>← COMMAND CENTER</button><div className="lesson-progress-copy"><span>LAYER {String(lesson.layer).padStart(2,'0')} // {lesson.topic.toUpperCase()}</span><b>{done?'MASTERED':'LEARN → TRY → MASTER'}</b></div></div><TutorGuide lesson={lesson} stats={stats} output={output} message={message} userCode={code} sound={progress.settings.sound} roastIntensity={progress.settings.roastIntensity} completed={done} onAdvance={advance}/><div className="lesson-code-zone"><section className="editor-panel"><div className="editor-head"><span>LIVE CODE // {lesson.difficulty}</span><span>{done?'✓ CONCEPT MASTERED':'WRITE THE SPELL'}</span></div><textarea spellCheck={false} value={code} onChange={e=>updateCode(e.target.value)} aria-label="Python code editor" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void run()}}}/><div className="editor-actions">{running?<button className="run-btn" onClick={stop}><Square size={14}/> STOP</button>:<button className="run-btn" onClick={()=>void run()} disabled={done}>{done?'MASTERED':'RUN CODE'} <Play size={14}/></button>}<button onClick={reset}><RotateCcw size={14}/> RESET</button><span className="shortcut">CTRL/CMD + ENTER</span></div><div className={`terminal-output ${output.startsWith('ERROR')?'error':''}`}><div>TERMINAL // LIVE</div><pre>{output}</pre></div>{message&&<div className={`feedback ${done?'success-row':''}`} aria-live="polite"><Sparkles size={15}/>{message}</div>}<div className="success-row"><span>Target: <b>{lesson.expectedOutput||'behavior test'}</b></span>{privateChecked&&<span>Private behavior verified <ShieldCheck size={15}/></span>}</div></section><aside className="lesson-side-note"><small>YOUR RULES IN THIS HELL</small><h3>Do not copy. Do not guess.</h3><p>Read the tutor. Predict the result. Write the smallest change you can explain. Then run it.</p><div className="hint-box"><span>ADAPTIVE HINT {lesson.hints.length?Math.min(hint+1,lesson.hints.length):0}/{lesson.hints.length}</span><p>{lesson.hints[Math.min(hint,Math.max(0,lesson.hints.length-1))]}</p><button onClick={reveal} disabled={hint>=Math.max(0,lesson.hints.length-1)}>REVEAL NEXT HINT</button></div><div className="mastery-mini">MASTERY <b>{Math.round(progress.attempts[lesson.id]?.mastery??0)}%</b><span>{stats?.attempts??0} attempts</span></div></aside></div></div>}
