import {useEffect,useMemo,useState,type Dispatch,type SetStateAction} from 'react';
import {Play,RotateCcw,Sparkles,ChevronRight,MessageCircle,ShieldCheck,Square} from 'lucide-react';
import type {Lesson} from '../domain/lessons';
import type {Progress} from '../types/progress';
import {evaluateLessonChallenge} from '../engine/challengeRunner';
import {PythonRunner} from '../execution/PythonRunner';
import {claimLessonReward,completeLesson,recordAttempt} from '../engine/progress';
import {XP_REWARDS} from '../engine/xp';
import {askMentor,createOpenAICompatibleProvider} from '../ai/mentor';
import {recommendedHintIndex,recordAttempt as adaptiveRecordAttempt,type MasteryRecord} from '../engine/adaptive';

type Props={lesson:Lesson;progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>;onBack:()=>void};
function adaptiveMap(progress:Progress):Record<string,MasteryRecord>{return Object.fromEntries(Object.entries(progress.attempts).map(([id,a])=>[id,{...a,mastery:Math.max(0,Math.min(1,a.mastery/100))}]));}
export function LessonWorkspace({lesson,progress,setProgress,onBack}:Props){
 const stats=progress.attempts[lesson.id];const adaptiveRecord=stats?{attempts:stats.attempts,successes:stats.successes,failures:stats.failures,hintsUsed:stats.hintsUsed,totalMs:stats.totalMs,lastOutcome:stats.lastOutcome,mastery:Math.max(0,Math.min(1,stats.mastery/100))}:{attempts:0,successes:0,failures:0,hintsUsed:0,totalMs:0,lastOutcome:null,mastery:0};const suggestedHint=stats?recommendedHintIndex(adaptiveRecord,lesson.hints.length):0;
 const [code,setCode]=useState(lesson.starterCode);const [output,setOutput]=useState('Runtime standing by.');const [running,setRunning]=useState(false);const [hint,setHint]=useState(suggestedHint);const [startedAt,setStartedAt]=useState(()=>Date.now());const [message,setMessage]=useState('');const [mentor,setMentor]=useState('');const [asking,setAsking]=useState(false);const [privateChecked,setPrivateChecked]=useState(false);const runner=useMemo(()=>new PythonRunner(),[]);
 useEffect(()=>()=>runner.dispose(),[runner]);useEffect(()=>{setCode(lesson.starterCode);setOutput('Runtime standing by.');setHint(recommendedHintIndex(stats?{attempts:stats.attempts,successes:stats.successes,failures:stats.failures,hintsUsed:stats.hintsUsed,totalMs:stats.totalMs,lastOutcome:stats.lastOutcome,mastery:Math.max(0,Math.min(1,stats.mastery/100))}:{attempts:0,successes:0,failures:0,hintsUsed:0,totalMs:0,lastOutcome:null,mastery:0},lesson.hints.length));setMessage('');setMentor('');setPrivateChecked(false);setStartedAt(Date.now())},[lesson.id,lesson.starterCode,lesson.hints.length]);
 const done=progress.completedLessons.includes(lesson.id);
 const run=async()=>{if(running||done)return;setRunning(true);setMessage('');setPrivateChecked(false);setOutput('Executing in isolated Python runtime…');const result=await runner.run(code);if(result.cancelled){setRunning(false);setMessage('Execution cancelled. No attempt was recorded.');setStartedAt(Date.now());return}const elapsed=Date.now()-startedAt;const judged=await evaluateLessonChallenge(lesson,code,result,runner);const success=judged.passed;const hintUsed=hint>0;const adaptive=adaptiveRecordAttempt(adaptiveMap(progress),lesson.id,success? 'success':result.timedOut?'timeout':'failure',elapsed,hintUsed).signal;setOutput(result.error?`ERROR\n${result.error}`:result.stdout||'(no output)');setPrivateChecked(Boolean(judged.hiddenChecked));setProgress(p=>{const wasCompleted=p.completedLessons.includes(lesson.id);const tracked=recordAttempt(p,lesson.id,success,hintUsed,elapsed);if(!success)return tracked;const completed=completeLesson(tracked,lesson.id);if(wasCompleted)return completed;const cleanXp=hintUsed?0:XP_REWARDS.noHint;return claimLessonReward(completed,lesson.id,XP_REWARDS.lesson+XP_REWARDS.challenge+cleanXp,!hintUsed)});setMessage(success?`CONCEPT CLEARED — ${judged.reason} ${adaptive.message}`:judged.reason+` ${adaptive.message}`);setRunning(false);setStartedAt(Date.now())};
 const stop=()=>{if(!running)return;runner.stop();setOutput('ERROR\nExecution stopped by user.');setMessage('Execution cancelled. You can edit the code and try again.');setRunning(false);setStartedAt(Date.now())};
 const ask=async()=>{if(asking)return;setAsking(true);const endpoint=import.meta.env.VITE_MENTOR_ENDPOINT;const model=import.meta.env.VITE_MENTOR_MODEL??'python-mentor';const provider=endpoint?createOpenAICompatibleProvider(endpoint,model):undefined;const reply=await askMentor({mode:'teacher',lessonTitle:lesson.title,topic:lesson.topic,userCode:code,output,mastery:progress.attempts[lesson.id]?.mastery??0,recentMistakes:stats?.lastOutcome&&stats.lastOutcome!=='success'?[stats.lastOutcome]:[]},provider);setMentor(reply.text);setAsking(false)};
 const reveal=()=>setHint(Math.min(hint+1,Math.max(0,lesson.hints.length-1)));
 return <div className="page"><button className="back-btn" onClick={onBack}>← COMMAND CENTER</button><div className="lesson-layout"><section className="lesson-brief"><div className="eyebrow">LAYER {String(lesson.layer).padStart(2,'0')} // {lesson.topic.toUpperCase()}</div><h1>{lesson.title}</h1><p className="lead">{lesson.explanation}</p><div className="teach-card"><strong>PYTHONSURA</strong><p>{lesson.roast}</p></div><div className="hint-box"><span>HINT {lesson.hints.length?Math.min(hint+1,lesson.hints.length):0}/{lesson.hints.length}</span><p>{lesson.hints[Math.min(hint,Math.max(0,lesson.hints.length-1))]}</p><button onClick={reveal} disabled={hint>=Math.max(0,lesson.hints.length-1)}>REVEAL NEXT HINT</button></div><div className="mastery-chip">MASTERY {Math.round(progress.attempts[lesson.id]?.mastery??0)}% {stats?.attempts?`• ${stats.attempts} ATTEMPTS`:''}</div><div className="challenge-safety"><ShieldCheck size={14}/> {privateChecked?'PRIVATE TEST PASSED':suggestedHint>0?'ADAPTIVE SUPPORT ACTIVE':'BEHAVIOR CHECKS ACTIVE'}</div><button className="mentor-button" onClick={()=>void ask()} disabled={asking}><MessageCircle size={15}/>{asking?'PYTHONSURA IS THINKING…':'ASK PYTHONSURA'}</button>{mentor&&<div className="mentor-reply"><small>PYTHONSURA</small><p>{mentor}</p></div>}</section><section className="editor-panel"><div className="editor-head"><span>CHALLENGE // {lesson.difficulty}</span><span>{done?'✓ MASTERED':'NOT YET DEAD'}</span></div><textarea spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} aria-label="Python code editor" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void run()}}}/><div className="editor-actions">{running?<button className="run-btn" onClick={stop}><Square size={14}/> STOP</button>:<button className="run-btn" onClick={()=>void run()} disabled={done}>{done?'MASTERED':'RUN CODE'} <Play size={14}/></button>}<button onClick={()=>{setCode(lesson.starterCode);setOutput('Runtime standing by.');setMessage('');setPrivateChecked(false);setStartedAt(Date.now())}}><RotateCcw size={14}/> RESET</button></div><div className={`terminal-output ${output.startsWith('ERROR')?'error':''}`}><div>TERMINAL OUTPUT</div><pre>{output}</pre></div>{message&&<div className={`feedback ${done?'success-row':''}`}><Sparkles size={15}/>{message}</div>}<div className="success-row"><span>Target: <b>{lesson.expectedOutput||'behavior test'}</b></span>{privateChecked&&<span>Private behavior verified <ShieldCheck size={15}/></span>}{done&&<ChevronRight size={15}/>}</div></section></div></div>}
