import {useEffect,useMemo,useState} from 'react';
import type {Dispatch,SetStateAction} from 'react';
import {Play,RotateCcw,Sparkles,ChevronRight} from 'lucide-react';
import type {Lesson} from '../domain/lessons';
import type {Progress} from '../types/progress';
import {PythonRunner} from '../execution/PythonRunner';
import {awardXp,completeLesson,recordAttempt} from '../engine/progress';
import {XP_REWARDS} from '../engine/xp';

type Props={lesson:Lesson;progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>;onBack:()=>void};
export function LessonWorkspace({lesson,progress,setProgress,onBack}:Props){
 const [code,setCode]=useState(lesson.starterCode);const [output,setOutput]=useState('Runtime standing by.');const [running,setRunning]=useState(false);const [hint,setHint]=useState(0);const [startedAt,setStartedAt]=useState(()=>Date.now());const [message,setMessage]=useState('');const runner=useMemo(()=>new PythonRunner(),[]);const stats=progress.attempts[lesson.id];
 useEffect(()=>()=>runner.dispose(),[runner]);useEffect(()=>{setCode(lesson.starterCode);setOutput('Runtime standing by.');setHint(stats?Math.min(stats.failures,Math.max(0,lesson.hints.length-1)):0);setMessage('');setStartedAt(Date.now())},[lesson.id,lesson.starterCode,lesson.hints.length]);
 const done=progress.completedLessons.includes(lesson.id);
 const run=async()=>{if(running||done)return;setRunning(true);setMessage('');setOutput('Executing in isolated Python runtime…');const result=await runner.run(code);const elapsed=Date.now()-startedAt;const success=!result.error&&result.stdout.trim()===lesson.expectedOutput.trim();const hintUsed=hint>0;setOutput(result.error?`ERROR\n${result.error}`:result.stdout||'(no output)');setProgress(p=>{const tracked=recordAttempt(p,lesson.id,success,hintUsed,elapsed);if(!success)return tracked;return awardXp(completeLesson(tracked,lesson.id),XP_REWARDS.challenge+(hintUsed?0:XP_REWARDS.noHint))});setMessage(success?'CONCEPT CLEARED — mastery updated.':result.error?.includes('timed out')?'Runtime stopped the execution. Fix the loop or reduce the work.':'Not cleared yet. Read the output, change one thing, and run again.');setRunning(false);setStartedAt(Date.now())};
 const reveal=()=>setHint(Math.min(hint+1,Math.max(0,lesson.hints.length-1)));
 return <div className="page"><button className="back-btn" onClick={onBack}>← COMMAND CENTER</button><div className="lesson-layout"><section className="lesson-brief"><div className="eyebrow">LAYER {String(lesson.layer).padStart(2,'0')} // {lesson.topic.toUpperCase()}</div><h1>{lesson.title}</h1><p className="lead">{lesson.explanation}</p><div className="teach-card"><strong>PYTHONSURA</strong><p>{lesson.roast}</p></div><div className="hint-box"><span>HINT {Math.min(hint+1,lesson.hints.length)}/{lesson.hints.length}</span><p>{lesson.hints[Math.min(hint,lesson.hints.length-1)]}</p><button onClick={reveal} disabled={hint>=lesson.hints.length-1}>REVEAL NEXT HINT</button></div><div className="mastery-chip">MASTERY {Math.round(progress.attempts[lesson.id]?.mastery??0)}% {stats?.attempts?`• ${stats.attempts} ATTEMPTS`:''}</div></section><section className="editor-panel"><div className="editor-head"><span>CHALLENGE // {lesson.difficulty}</span><span>{done?'✓ MASTERED':'NOT YET DEAD'}</span></div><textarea spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} aria-label="Python code editor" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void run()}}}/><div className="editor-actions"><button className="run-btn" onClick={()=>void run()} disabled={running||done}>{running?'RUNNING…':done?'MASTERED':'RUN CODE'} <Play size={14}/></button><button onClick={()=>{setCode(lesson.starterCode);setOutput('Runtime standing by.');setMessage('');setStartedAt(Date.now())}}><RotateCcw size={14}/> RESET</button></div><div className={`terminal-output ${output.startsWith('ERROR')?'error':''}`}><div>TERMINAL OUTPUT</div><pre>{output}</pre></div>{message&&<div className="feedback"><Sparkles size={15}/>{message}</div>}<div className="success-row"><span>Target: <b>{lesson.expectedOutput}</b></span>{done&&<ChevronRight size={15}/>}</div></section></div></div>}
