import {useRef,useState,type ChangeEvent,type Dispatch,type SetStateAction} from 'react';
import type {Progress} from '../types/progress';
import {playSfx} from '../engine/audio';

type Props={progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>;onClose:()=>void};
const KEY='python-from-hell:rpg-progress:v3';
function isProgressSnapshot(value:unknown):value is Progress{if(!value||typeof value!=='object')return false;const p=value as Partial<Progress>;return p.version===3&&typeof p.xp==='number'&&Number.isFinite(p.xp)&&typeof p.currentLessonId==='string'&&Array.isArray(p.completedLessons)&&Array.isArray(p.lessonRewards)&&Array.isArray(p.achievements)&&Array.isArray(p.completedBosses)&&Array.isArray(p.projectRewards)&&Array.isArray(p.debugRewards)&&typeof p.attempts==='object'&&p.attempts!==null&&typeof p.settings==='object'&&p.settings!==null&&typeof p.interview==='object'&&p.interview!==null}
export function SettingsPanel({progress,setProgress,onClose}:Props){
 const [message,setMessage]=useState('');const inputRef=useRef<HTMLInputElement>(null);
 const update=<K extends keyof Progress['settings']>(key:K,value:Progress['settings'][K])=>setProgress(p=>({...p,settings:{...p.settings,[key]:value}}));
 const toggleSound=(enabled:boolean)=>{update('sound',enabled);if(enabled)playSfx('achievement')};
 const exportSave=()=>{const blob=new Blob([JSON.stringify(progress,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='python-from-hell-save.json';link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('SAVE EXPORTED. KEEP IT SOMEWHERE SAFE.')};
 const importSave=()=>inputRef.current?.click();
 const handleImport=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()) as unknown;if(!isProgressSnapshot(parsed))throw new Error('invalid save');localStorage.setItem(KEY,JSON.stringify(parsed));setProgress(parsed);setMessage('SAVE RESTORED. THE DESCENT CONTINUES.')}catch{setMessage('INVALID SAVE FILE. NOTHING WAS CHANGED.')}finally{event.target.value=''}};
 const reset=()=>{localStorage.removeItem('python-from-hell:rpg-progress:v3');localStorage.removeItem('python-from-hell:rpg-progress:v2');localStorage.removeItem('python-from-hell:rpg-progress:v1');localStorage.removeItem('python-from-hell:entered');location.reload()};
 return <div className="settings-overlay" role="dialog" aria-modal="true" aria-label="Game settings"><section className="settings-panel"><div className="panel-title"><span>HELL SETTINGS</span><button className="back-btn" onClick={onClose}>CLOSE</button></div><h2>Control the suffering.</h2><label>ROAST INTENSITY<select value={progress.settings.roastIntensity} onChange={e=>update('roastIntensity',e.target.value as Progress['settings']['roastIntensity'])}><option value="MILD">MILD</option><option value="SAVAGE">SAVAGE</option><option value="APOCALYPSE">APOCALYPSE</option></select></label><label className="toggle-row"><span>SOUND EFFECTS</span><input type="checkbox" checked={progress.settings.sound} onChange={e=>toggleSound(e.target.checked)}/></label><label className="toggle-row"><span>REDUCED MOTION</span><input type="checkbox" checked={progress.settings.reducedMotion} onChange={e=>update('reducedMotion',e.target.checked)}/></label><div className="save-tools"><button onClick={exportSave}>EXPORT SAVE</button><button onClick={importSave}>IMPORT SAVE</button><input ref={inputRef} type="file" accept="application/json,.json" onChange={handleImport} hidden/></div>{message&&<p className="settings-message" role="status">{message}</p>}<button className="danger-button" onClick={reset}>ERASE LOCAL SAVE</button></section></div>;
}
