import {readFile,readdir} from 'node:fs/promises';
const [requirements,lessons,curriculum,app,lessonUi,debugging,interview,bosses,projects,projectUi,settingsUi,saveUi,adaptive,progress,xp,runner,main,mobileCss,packageJson,srcEntries,interviewUi,tutorUi,mentorUi,tutorCss,viteConfig,designSystem,hellGate,hellGateCss,gauntlet,readme,world3d,hellAudio,reactions]=await Promise.all([
 readFile('PYTHON_FROM_HELL_REQUIREMENTS.md','utf8'),readFile('src/domain/lessons.ts','utf8'),readFile('src/domain/curriculum.ts','utf8'),readFile('src/AppFinal.tsx','utf8'),readFile('src/components/LessonWorkspace.tsx','utf8'),readFile('src/domain/debugging.ts','utf8'),readFile('src/domain/interview.ts','utf8'),readFile('src/domain/bosses.ts','utf8'),readFile('src/domain/projects.ts','utf8'),readFile('src/components/ProjectFactory.tsx','utf8'),readFile('src/components/SettingsPanel.tsx','utf8'),readFile('src/components/SaveTransferPanel.tsx','utf8'),readFile('src/engine/adaptive.ts','utf8'),readFile('src/engine/progress.ts','utf8'),readFile('src/engine/xp.ts','utf8'),readFile('src/execution/PythonRunner.ts','utf8'),readFile('src/main.tsx','utf8'),readFile('src/mobile-polish.css','utf8'),readFile('package.json','utf8'),readdir('src'),readFile('src/components/InterviewArena.tsx','utf8'),readFile('src/components/TutorGuide.tsx','utf8'),readFile('src/ai/mentor.ts','utf8'),readFile('src/tutor.css','utf8'),readFile('vite.config.ts','utf8'),readFile('design-system/MASTER.md','utf8'),readFile('src/components/HellGateExperience.tsx','utf8'),readFile('src/hellgate.css','utf8'),readFile('src/domain/lessonGauntlet.ts','utf8'),readFile('README.md','utf8'),readFile('src/components/HellWorld3D.tsx','utf8'),readFile('src/engine/hellAudio.ts','utf8'),readFile('src/domain/hellReactions.ts','utf8')
]);
const packageData=JSON.parse(packageJson);void projectUi;void mobileCss;void viteConfig;for(const layer of Array.from({length:12},(_,i)=>i+1)){if(!new RegExp(`layer:\\s*${layer}\\b`).test(lessons))throw new Error(`Missing lesson coverage for layer ${layer}`);if(!new RegExp(`number:\\s*${layer}\\b`).test(curriculum))throw new Error(`Missing curriculum layer ${layer}`)}
const lessonCount=(lessons.match(/id:\s*['"]l/g)||[]).length,debugCount=(debugging.match(/id:\s*['"]/g)||[]).length,interviewCount=(interview.match(/q\(\s*['"]i/g)||[]).length,bossCount=(bosses.match(/\bb\(\s*['"]/g)||[]).length,phaseCount=(bosses.match(/\{\s*name:\s*['"][^'"]+['"],\s*objective:/g)||[]).length,projectCount=(projects.match(/\bid:\s*['"][^'"]+['"],\s*tier:\s*['"]/g)||[]).length,projectValidationCount=(projects.match(/validation:\s*\{\s*requiredPatterns:/g)||[]).length,projectRewardCount=(projects.match(/rewardXp:\s*150/g)||[]).length,gauntletCount=(gauntlet.match(/id:\s*\d+/g)||[]).length;
if(lessonCount!==70)throw new Error(`Expected 70 lessons, found ${lessonCount}`);if(debugCount<8)throw new Error(`Expected >=8 debugging cases, found ${debugCount}`);if(interviewCount!==30)throw new Error(`Expected 30 interview questions, found ${interviewCount}`);if(bossCount!==7||phaseCount!==21)throw new Error(`Expected 7 bosses / 21 phases, found ${bossCount}/${phaseCount}`);if(projectCount!==6||projectValidationCount!==6||projectRewardCount!==6)throw new Error('Project contract count/rewards mismatch');if(packageData.version!=='1.0.0'||!packageData.engines?.node?.includes('24')||!packageData.dependencies?.motion||!packageData.dependencies?.three)throw new Error('Package contract mismatch');if(gauntletCount!==20)throw new Error('Every lesson must have a 20-step mastery gauntlet');
if(srcEntries.includes('App.tsx')||srcEntries.includes('AppV2.tsx')||srcEntries.includes('AppV3.tsx'))throw new Error('Obsolete application entrypoint remains');if(srcEntries.includes('CosmeticHud.tsx'))throw new Error('Redundant cosmetic telemetry HUD remains');if(!/No fake interaction|fake interaction|fake progress/i.test(requirements))throw new Error('Anti-fake rule missing');
if(!/HellGateExperience/.test(main)||!/hellgate:v(?:2|3)/.test(main)||!/wakeTitle/.test(hellGate)||!/arrivalTitle/.test(hellGate)||!/portalTitle/.test(hellGate)||!/guideTitle/.test(hellGate)||!/hinglish/.test(hellGate)||!/ACCEPT THE DESCENT/.test(hellGate)||!/ENTER THE DUNGEON/.test(hellGate))throw new Error('Story-first HellGate contract incomplete');if(!/screen-shake|shake/.test(hellGateCss)||!/(jaw-portal|HellWorld3D)/.test(hellGateCss))throw new Error('Purposeful HellGate cinematic motion missing');if(!/setExperienceLanguage/.test(hellGate)||!/getExperienceLanguage/.test(tutorUi)||!/const language = getExperienceLanguage\(\)/.test(tutorUi)||!/Respond primarily in that language/.test(mentorUi))throw new Error('Language propagation missing');
if(!/HellWorld3D/.test(hellGate)||!/THREE\.WebGLRenderer/.test(world3d)||!/PerspectiveCamera/.test(world3d)||!/FogExp2/.test(world3d)||!/createPythosura/.test(world3d)||!/mini/.test(world3d)||!/portal/.test(world3d))throw new Error('Real-time 3D Hell world is incomplete');if(!/startAmbience/.test(hellAudio)||!/quake/.test(hellAudio)||!/roar/.test(hellAudio)||!/portal/.test(hellAudio)||!/fireCrackle/.test(hellAudio)||!/chain/.test(hellAudio))throw new Error('Layered Hell audio engine is incomplete');if(!/pickHellReaction/.test(reactions)||!/repeated-failure/.test(reactions)||!/runtime-error/.test(reactions)||!/success/.test(reactions)||!/mastery/.test(reactions))throw new Error('Context-aware reaction bank is incomplete');
if(!/gauntletStepForAttempts/.test(tutorUi)||!/TRIAL/.test(tutorUi)||!/MASTER/.test(tutorUi)||!/pickHellReaction/.test(tutorUi))throw new Error('Progressive mastery/reactive tutor contract missing');
if(!/evaluateLessonChallenge/.test(lessonUi)||!/XP_REWARDS\.lesson\s*\+\s*XP_REWARDS\.challenge/.test(lessonUi)||!/claimLessonReward/.test(lessonUi)||!/runner\.stop/.test(lessonUi)||!/timedOut/.test(lessonUi)||!/successes\s*>=\s*3/.test(lessonUi)||!/aria-live=\"polite\"/.test(lessonUi)||!/lesson-drafts:v1/.test(lessonUi)||!/TutorGuide/.test(lessonUi)||!/onHintUsed/.test(lessonUi))throw new Error('Lesson runtime wiring incomplete');
if(!/roastIntensity/.test(tutorUi)||!/roast\(/.test(tutorUi)||!/teacher-disturbance/.test(tutorUi)||!/voiceManager/.test(tutorUi)||!/QUICK/.test(tutorUi)||!/askMentor/.test(tutorUi)||!/TeachingMode/.test(tutorUi)||!/simple|analogy|visual|code|interactive/.test(tutorUi)||!/gauntletStepForAttempts/.test(tutorUi))throw new Error('Living teacher/roast/adaptive help incomplete');
if(!/runner\.stop/.test(app)||!/evaluateBossPhase/.test(app)||!/claimBossReward/.test(app)||!/InterviewArena/.test(app))throw new Error('Active non-lesson logic incomplete');if(/alert\s*\(/.test(app))throw new Error('Fake alert interaction remains');if(/onClick=\{\(\)=>\{\}\}/.test(app))throw new Error('Empty click handler detected');if(!/lesson:\\s*20[\\s\\S]*challenge:\\s*30[\\s\\S]*noHint:\\s*15[\\s\\S]*debug:\\s*40[\\s\\S]*boss:\\s*100[\\s\\S]*project:\\s*150[\\s\\S]*interview:\\s*50/.test(xp))throw new Error('XP rewards mismatch');if(!/timedOut/.test(runner)||!/cancelled/.test(runner)||!/if\(this\.pending\)this\.stop/.test(runner))throw new Error('Runtime cancellation/warm worker contract missing');if(!/recordAttempt as adaptiveRecordAttempt/.test(progress)||!/signalFor/.test(adaptive))throw new Error('Adaptive mastery wiring missing');
if(!/SaveTransferPanel/.test(settingsUi)||!/EXPORT SAVE/.test(saveUi)||!/IMPORT SAVE/.test(saveUi)||!/validProgress/.test(saveUi)||!/Nothing was changed/.test(saveUi))throw new Error('Portable save contract missing');if(!/mobile-polish\.css/.test(main)||!/save-polish\.css/.test(main)||!/interview-polish\.css/.test(main)||!/tutor\.css/.test(main)||!/hellgate\.css/.test(main))throw new Error('Required styles missing');if(!/North-star experience|Living Classroom|Pythonsura personality/.test(designSystem)||!/Every screen should answer/.test(designSystem))throw new Error('Master design system missing');if(!/motion\/react/.test(tutorUi)||!/useReducedMotion/.test(tutorUi)||!/lesson-page\{position:fixed/.test(tutorCss)||!/meme-strip/.test(tutorCss)||!/prefers-reduced-motion/.test(tutorCss))throw new Error('Motion-first tutor UX missing');if(!/RANKS/.test(interviewUi)||!/PYTHON INTERN/.test(interviewUi)||!/HELL TOURIST/.test(interviewUi)||!/CODE IMP/.test(interviewUi)||!/PYTHON HERETIC/.test(interviewUi)||!/RUNTIME REAPER/.test(interviewUi)||!/DEBUGGING DEMON/.test(interviewUi)||!/CPYTHON NECROMANCER/.test(interviewUi)||!/PYTHON OVERLORD/.test(interviewUi)||!/RETRY FOR 1 POINT/.test(interviewUi))throw new Error('Interview rank/retry contract missing');
if(!/HellGate|Living Classroom|Hinglish|20-step|gauntlet|Pythonsura/.test(readme))throw new Error('README does not describe the current experience');
console.log(`Content checks passed: ${lessonCount} lessons, ${debugCount} debugging cases, ${interviewCount} interview questions, ${bossCount} bosses / ${phaseCount} phases, ${projectCount} executable projects, 12 Hell layers, ${gauntletCount} gauntlet steps.`);
