import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Bug,ChevronRight,Flame,Home,Play,Settings,Shield,Skull,Sparkles,Swords,Terminal,Trophy} from 'lucide-react';
import {hellLayers} from './domain/curriculum';
import {lessonCatalog} from './domain/lessons';
import {bosses} from './domain/bosses';
import {interviewQuestions} from './domain/interview';
import {projects} from './domain/projects';
import {storyEvents,nextStoryEvent} from './domain/story';
import {createInitialProgress,loadProgress,saveProgress,awardXp} from './engine/progress';
import {levelFromXp,xpToNext,XP_REWARDS} from './engine/xp';
import {grantAchievement,ACHIEVEMENTS} from './engine/achievements';
import {unlockedLayerCount} from './engine/unlocks';
import {LessonWorkspace} from './components/LessonWorkspace';
import type {Progress} from './types/progress';
import {PythonRunner} from './execution/PythonRunner';

type View='command'|'lesson'|'curriculum'|'coding'|'debugging'|'bosses'|'interview'|'projects';
const nav:[View,typeof Home,string][]=[['command',Home,'Command Center'],['curriculum',BookOpen,'Curriculum'],['coding',Terminal,'Coding Arena'],['debugging',Bug,'Debugging Dungeon'],['bosses',Swords,'Boss Battles'],['interview',Shield,'Interview Arena'],['projects',Trophy,'Project Factory']];

export default function App(){
 const [progress,setProgress]=useState<Progress>(()=>loadProgress()??createInitialProgress());
 const [view,setView]=useState<View>('command'); const [selectedLesson,setSelectedLesson]=useState(lessonCatalog[0].id);
 const [gate,setGate]=useState(()=>localStorage.getItem('python-from-hell:entered')!=='yes');
 useEffect(()=>saveProgress(progress),[progress]);
 const unlocked=unlockedLayerCount(progress.completedLessons); const lesson=lessonCatalog.find(l=>l.id===selectedLesson)??lessonCatalog[0];
 const openLesson=(id=lessonCatalog.find(l=>l.layer===unlocked)?.id??lessonCatalog[0].id)=>{setSelectedLesson(id);setView('lesson')};
 const award=(amount:number)=>setProgress(p=>awardXp(p,amount));
 if(gate)return <HellGate onEnter={()=>{localStorage.setItem('python-from-hell:entered','yes');setGate(false)}}/>;
 return <div className="app-shell"><Sidebar view={view} onNavigate={setView}/><main className="main-stage"><Topbar progress={progress}/>{view==='command'&&<CommandCenter progress={progress} unlocked={unlocked} onLesson={openLesson} onNavigate={setView}/>} {view==='lesson'&&<LessonWorkspace lesson={lesson} progress={progress} setProgress={setProgress} onBack={()=>setView('command')}/>} {view==='curriculum'&&<Curriculum unlocked={unlocked} completed={progress.completedLessons} onLesson={openLesson}/>} {view==='coding'&&<CodingArena award={award}/>} {view==='debugging'&&<DebuggingDungeon award={award}/>} {view==='bosses'&&<BossChamber progress={progress} setProgress={setProgress}/>} {view==='interview'&&<InterviewArena progress={progress} setProgress={setProgress}/>} {view==='projects'&&<ProjectFactory progress={progress} setProgress={setProgress}/>}</main></div>;
}

function HellGate({onEnter}:{onEnter:()=>void}){return <main className="gate-shell"><div className="ember-field" aria-hidden="true">{Array.from({length:10},(_,i)=><i key={i}/>)}</div><header className="brand"><Flame size={20}/><span>PYTHON <b>FROM HELL</b></span><small>v0.3 // THE DESCENT</small></header><section className="gate-content"><div className="eyebrow"><span className="pulse"/> DEVELOPER HELL // GATE 01</div><h1>WELCOME TO<br/><em>PYTHON FROM HELL.</em></h1><p className="hook">Python is easy.</p><p className="pause">That's what they told you.</p><button className="primary-cta" onClick={onEnter}>ENTER HELL <ChevronRight size={20}/></button><p className="microcopy">No fake progress. No fake buttons. You actually have to learn.</p></section><footer className="gate-footer"><span>PYTHONSURA // MENTOR ONLINE</span><span>PYTHON RUNTIME: READY</span><span>12 LAYERS // 1 WAY OUT</span></footer></main>}
function Sidebar({view,onNavigate}:{view:View;onNavigate:(v:View)=>void}){return <aside className="sidebar"><div className="brand compact"><Flame size={20}/><span>PYTHON <b>FROM HELL</b></span></div><div className="layer-badge"><small>YOU ARE HERE</small><strong>LAYER {String(unlockedLayerCount([])).padStart(2,'0')}</strong><span>THE DESCENT</span></div><nav>{nav.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>onNavigate(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="mentor-mini"><div className="avatar">P</div><div><small>MENTOR</small><strong>PYTHONSURA</strong><span>online • judging</span></div></div></aside>}
function Topbar({progress}:{progress:Progress}){return <header className="topbar"><div><p className="eyebrow">COMMAND NETWORK</p><h2>Good morning, <em>heretic.</em></h2></div><div className="top-stats"><span>LVL <b>{String(levelFromXp(progress.xp)).padStart(2,'0')}</b></span><span>XP <b>{progress.xp}</b></span><span>STREAK <b>{progress.streak}</b></span><button title="Settings"><Settings size={16}/></button></div></header>}
function CommandCenter({progress,unlocked,onLesson,onNavigate}:{progress:Progress;unlocked:number;onLesson:(id?:string)=>void;onNavigate:(v:View)=>void}){const next=lessonCatalog.find(l=>!progress.completedLessons.includes(l.id))??lessonCatalog[0];const story=nextStoryEvent(progress.completedLessons.length);return <div className="page"><section className="hero-panel"><div><div className="eyebrow"><span className="pulse"/> NEXT MISSION</div><h1>{next.title}</h1><p>{next.brief}</p><div className="mission-meta"><span>{next.minutes} MIN</span><span>{next.difficulty}</span><span>+{XP_REWARDS.lesson} XP</span></div><button className="primary-cta small" onClick={()=>onLesson(next.id)}><Play size={15}/> START LESSON</button></div><CodePreview code={next.starterCode}/></section><div className="stat-grid"><Stat label="HELL LAYER" value={`0${unlocked}`} sub={hellLayers[unlocked-1]?.name??'THE CORE'}/><Stat label="SOUL LEVEL" value={String(levelFromXp(progress.xp)).padStart(2,'0')} sub="PYTHON INTERN"/><Stat label="XP TO NEXT" value={String(xpToNext(progress.xp))} sub="KEEP DIGGING"/><Stat label="STREAK" value={`${progress.streak} DAYS`} sub="CONSISTENCY > CHAOS"/></div><div className="feature-grid"><Feature icon={BookOpen} title="WHAT SHOULD I DO NEXT?" text="The engine picked the next unfinished lesson." action="OPEN MISSION" onClick={()=>onLesson(next.id)}/><Feature icon={Bug} title="DEBUGGING DUNGEON" text="Break the bug down instead of begging for the answer." action="ENTER DUNGEON" onClick={()=>onNavigate('debugging')}/><Feature icon={Swords} title="BOSS BATTLES" text="Major layers end with a fight." action="VIEW BOSSES" onClick={()=>onNavigate('bosses')}/></div><div className="panel story-panel"><div className="panel-title"><span>STORY SIGNAL</span><small>{story?.id??'CORE'}</small></div><h3>{story?.title??'The Core is listening.'}</h3><p>{story?.text??'Keep descending. The runtime has not forgotten you.'}</p></div></div>}
function Stat({label,value,sub}:{label:string;value:string;sub:string}){return <div className="stat"><small>{label}</small><strong>{value}</strong><span>{sub}</span></div>}
function Feature({icon:Icon,title,text,action,onClick}:{icon:typeof Home;title:string;text:string;action:string;onClick:()=>void}){return <button className="feature" onClick={onClick}><Icon/><small>{title}</small><p>{text}</p><b>{action} <ChevronRight size={14}/></b></button>}
function CodePreview({code}:{code:string}){return <div className="lesson-terminal"><div className="terminal-top"><span/><span/><span/><label>lesson.py</label></div><pre>{code}</pre></div>}
function Curriculum({unlocked,completed,onLesson}:{unlocked:number;completed:string[];onLesson:(id:string)=>void}){return <div className="page"><div className="section-heading"><div><div className="eyebrow">THE DESCENT</div><h1>12 LAYERS OF HELL</h1></div><span>{completed.length} LESSONS CLEARED</span></div><div className="curriculum-grid">{hellLayers.map(layer=><article key={layer.id} className={`layer-card ${layer.number<=unlocked?'open':'locked'}`}><div className="layer-number">{String(layer.number).padStart(2,'0')}</div><div><small>LAYER {String(layer.number).padStart(2,'0')}</small><h3>{layer.name}</h3><p>{layer.tagline}</p><div className="topic-list">{layer.topics.map(t=><span key={t}>{t}</span>)}</div>{layer.number<=unlocked?<button onClick={()=>{const id=lessonCatalog.find(l=>l.layer===layer.number)?.id;if(id)onLesson(id)}}>ENTER LAYER <ChevronRight size={14}/></button>:<span className="locked-label">LOCKED — CLEAR CURRENT LAYER</span>}</div></article>)}</div></div>}
function CodingArena({award}:{award:(n:number)=>void}){const [code,setCode]=useState('def greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("heretic"))');const [out,setOut]=useState('');const [running,setRunning]=useState(false);const runner=useMemo(()=>new PythonRunner(),[]);useEffect(()=>()=>runner.dispose(),[runner]);return <div className="page"><div className="section-heading"><div><div className="eyebrow">CODING ARENA</div><h1>WRITE. RUN. SURVIVE.</h1></div></div><div className="arena"><textarea spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} aria-label="Coding arena editor"/><div className="arena-side"><button className="run-btn" disabled={running} onClick={async()=>{setRunning(true);const r=await runner.run(code);setOut(r.error?`ERROR\n${r.error}`:r.stdout||'(no output)');setRunning(false);if(!r.error)award(XP_REWARDS.challenge)}}>{running?'RUNNING…':'RUN PYTHON'} <Play size={15}/></button><div className="terminal-output"><div>OUTPUT</div><pre>{out||'Your output will appear here.'}</pre></div></div></div></div>}
function DebuggingDungeon({award}:{award:(n:number)=>void}){const [code,setCode]=useState('def add_item(item, bucket=[]):\n    bucket.append(item)\n    return bucket\n\nprint(add_item("fire"))\nprint(add_item("brimstone"))');const [result,setResult]=useState('');const [running,setRunning]=useState(false);const runner=useMemo(()=>new PythonRunner(),[]);useEffect(()=>()=>runner.dispose(),[runner]);const run=async()=>{setRunning(true);const r=await runner.run(code);setResult(r.error?`ERROR\n${r.error}`:r.stdout||'(no output)');setRunning(false);if(!r.error&&r.stdout.trim()==='[\'fire\']\n[\'fire\', \'brimstone\']')award(XP_REWARDS.debug)};return <div className="page"><div className="section-heading"><div><div className="eyebrow">DEBUGGING DUNGEON // CASE 001</div><h1>THE MUTABLE DEFAULT</h1></div></div><div className="debug-grid"><section className="broken"><div className="trace-label">BROKEN PROGRAM</div><textarea spellCheck={false} value={code} onChange={e=>setCode(e.target.value)}/><button className="run-btn" disabled={running} onClick={()=>void run()}>{running?'RUNNING…':'RUN & INSPECT'}</button><div className="terminal-output"><div>TRACE</div><pre>{result||'Run the broken program first.'}</pre></div></section><section className="method"><span>PYTHONSURA // DEBUGGING METHOD</span><h2>Don't patch the symptom.</h2><ol><li>Reproduce the bug.</li><li>Read the traceback/output.</li><li>Identify state that survives between calls.</li><li>Make the smallest safe fix.</li></ol><div className="hint-box"><span>HINT</span><p>Use <code>None</code> as a sentinel and create a new list inside the function when needed.</p></div></section></div></div>}
function BossChamber({progress,setProgress}:{progress:Progress;setProgress:React.Dispatch<React.SetStateAction<Progress>>}){const [phase,setPhase]=useState(0);const boss=bosses.find(b=>progress.unlockedBosses.includes(b.id))??bosses[0];const cleared=progress.completedBosses.includes(boss.id);const action=()=>{if(cleared)return;const next=phase+1;if(next<boss.phases.length)setPhase(next);else setProgress(p=>({...awardXp({...p,completedBosses:[...p.completedBosses,boss.id],achievements:grantAchievement(p.achievements,ACHIEVEMENTS.BOSS_SLAYER)},boss.rewardXp),unlockedBosses:p.unlockedBosses}))};return <div className="page"><div className="section-heading"><div><div className="eyebrow">BOSS CHAMBER</div><h1>{boss.name}</h1></div><span>{cleared?'SLAIN':`PHASE ${phase+1}/${boss.phases.length}`}</span></div><div className="boss-panel"><div className="boss-sigil"><Skull size={60}/><span>{boss.name}</span></div><div><div className="eyebrow">{boss.title}</div><h2>{boss.phases[phase]?.name}</h2><p>{boss.phases[phase]?.objective}</p><small>CONCEPT // {boss.phases[phase]?.concept}</small><div className="mission-meta"><span>REWARD +{boss.rewardXp} XP</span></div><button className="primary-cta small" onClick={action}>{cleared?'BOSS SLAIN':phase+1===boss.phases.length?'DEAL FINAL BLOW':'SURVIVE PHASE'} <Swords size={16}/></button></div></div></div>}
function InterviewArena({progress,setProgress}:{progress:Progress;setProgress:React.Dispatch<React.SetStateAction<Progress>>}){const index=Math.min(progress.interview.round,interviewQuestions.length-1);const q=interviewQuestions[index];const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState('');const submit=()=>{const normalized=answer.toLowerCase();const hits=q.expectedPoints.filter(point=>point.split(' ').some(word=>word.length>4&&normalized.includes(word.toLowerCase()))).length;const score=Math.max(0,hits);setFeedback(hits>=2?'Strong answer. Defend it with an example.':'Too thin. Explain the mechanism, not just the slogan.');setProgress(p=>{const nextRound=Math.min(p.interview.round+1,interviewQuestions.length);const total=p.interview.score+score;const rank=total>=10?'PYTHON HERETIC':total>=6?'HELL TOURIST':'PYTHON INTERN';return awardXp({...p,interview:{round:nextRound,score:total,rank}},XP_REWARDS.interview)});setAnswer('')};return <div className="page"><div className="section-heading"><div><div className="eyebrow">INTERVIEW BATTLE ARENA</div><h1>THE INTERVIEWER DEMON</h1></div><span>ROUND {Math.min(progress.interview.round+1,interviewQuestions.length)}/{interviewQuestions.length}</span></div>{progress.interview.round>=interviewQuestions.length?<div className="panel"><h2>ARENA CLEARED.</h2><p>Rank: {progress.interview.rank}. Score: {progress.interview.score}/{interviewQuestions.length*2}.</p></div>:<div className="interview-card"><div className="demon"><Skull/><span>{q.tier.toUpperCase()}</span></div><h2>{q.prompt}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Answer like your rent depends on it…"/><button className="primary-cta small" disabled={!answer.trim()} onClick={submit}>SUBMIT ANSWER <ChevronRight size={15}/></button><p>{feedback||`Follow-up: ${q.followUp}`}</p></div>}</div>}
function ProjectFactory({progress,setProgress}:{progress:Progress;setProgress:React.Dispatch<React.SetStateAction<Progress>>}){const [active,setActive]=useState(projects[0]?.id??'');const project=projects.find(p=>p.id===active)??projects[0];const state=progress.projects[project.id]??{started:false,completed:false,milestones:[]};const toggleMilestone=(id:string)=>setProgress(p=>{const cur=p.projects[project.id]??{started:true,completed:false,milestones:[]};const milestones=cur.milestones.includes(id)?cur.milestones.filter(x=>x!==id):[...cur.milestones,id];const completed=milestones.length===project.milestones.length;return awardXp({...p,projects:{...p.projects,[project.id]:{started:true,completed,milestones}}},completed&&!cur.completed?XP_REWARDS.project:0)});return <div className="page"><div className="section-heading"><div><div className="eyebrow">PROJECT FACTORY</div><h1>BUILD SOMETHING THAT BREAKS</h1></div></div><div className="project-grid">{projects.map(p=><button key={p.id} className={`project-card ${p.id===project.id?'selected':''}`} onClick={()=>setActive(p.id)}><small>{p.difficulty}</small><h2>{p.name}</h2><p>{p.brief}</p></button>)}</div><section className="project-workspace"><small>{project.difficulty}</small><h2>{project.name}</h2><p>{project.brief}</p><div className="milestones">{project.milestones.map(m=><label key={m.id}><input type="checkbox" checked={state.milestones.includes(m.id)} onChange={()=>toggleMilestone(m.id)}/><span>{m.title}</span></label>)}</div><div className="hint-box"><span>FACTORY RULE</span><p>{project.firstTask}</p></div></section></div>}
