import {useEffect,useState} from 'react';
import {BookOpen,Bug,ChevronRight,Flame,Home,Play,RotateCcw,Settings,Shield,Swords,Square,Terminal,Trophy,type LucideIcon} from 'lucide-react';
import type {Dispatch,SetStateAction} from 'react';
import {hellLayers} from './domain/curriculum';
import {lessonCatalog} from './domain/lessons';
import {debuggingCases} from './domain/debugging';
import {bosses,type BossPhase} from './domain/bosses';
import {interviewQuestions} from './domain/interview';
import {nextStoryEvent} from './domain/story';
import {createInitialProgress,loadProgress,saveProgress,claimCodingReward,claimDebugReward,claimBossReward,setBossPhase,claimInterviewReward} from './engine/progress';
import {evaluateBossPhase} from './engine/bossRunner';
import {levelFromXp,xpToNext,XP_REWARDS} from './engine/xp';
import {grantAchievement,ACHIEVEMENTS} from './engine/achievements';
import {unlockedLayerCount} from './engine/unlocks';
import {LessonWorkspace} from './components/LessonWorkspace';
import {ProjectFactory as ProjectFactoryReal} from './components/ProjectFactory';
import {SettingsPanel} from './components/SettingsPanel';
import {PythonRunner} from './execution/PythonRunner';
import type {Progress} from './types/progress';

type View='command'|'curriculum'|'lesson'|'coding'|'debugging'|'bosses'|'interview'|'projects';
const nav:Array<[View,LucideIcon,string]>=[['command',Home,'Command Center'],['curriculum',BookOpen,'Curriculum'],['coding',Terminal,'Coding Arena'],['debugging',Bug,'Debugging Dungeon'],['bosses',Swords,'Boss Battles'],['interview',Shield,'Interview Arena'],['projects',Trophy,'Project Factory']];

export default function AppFinal(){
 const [progress,setProgress]=useState<Progress>(()=>loadProgress()??createInitialProgress());
 const [view,setView]=useState<View>('command');
 const [lessonId,setLessonId]=useState(progress.currentLessonId);
 const [entered,setEntered]=useState(()=>localStorage.getItem('python-from-hell:entered')==='yes');
 const [settings,setSettings]=useState(false);
 useEffect(()=>saveProgress(progress),[progress]);
 const unlocked=unlockedLayerCount(progress.completedLessons);
 const lesson=lessonCatalog.find(l=>l.id===lessonId)??lessonCatalog.find(l=>l.layer===unlocked)??lessonCatalog[0];
 const openLesson=(id:string)=>{setLessonId(id);setProgress(p=>({...p,currentLessonId:id}));setView('lesson')};
 if(!entered)return <HellGate onEnter={()=>{localStorage.setItem('python-from-hell:entered','yes');setEntered(true)}}/>;
 return <div className="app-shell"><Sidebar view={view} unlocked={unlocked} onNavigate={setView}/><main className="main-stage"><Topbar progress={progress} onSettings={()=>setSettings(true)}/>{view==='command'&&<CommandCenter progress={progress} unlocked={unlocked} onLesson={openLesson} onNavigate={setView}/>} {view==='curriculum'&&<Curriculum unlocked={unlocked} completed={progress.completedLessons} onLesson={openLesson}/>} {view==='lesson'&&<LessonWorkspace lesson={lesson} progress={progress} setProgress={setProgress} onBack={()=>setView('command')}/>} {view==='coding'&&<CodingArena progress={progress} setProgress={setProgress}/>} {view==='debugging'&&<DebuggingDungeon progress={progress} setProgress={setProgress}/>} {view==='bosses'&&<BossChamber progress={progress} unlocked={unlocked} setProgress={setProgress}/>} {view==='interview'&&<InterviewArena progress={progress} setProgress={setProgress}/>} {view==='projects'&&<ProjectFactoryReal progress={progress} setProgress={setProgress}/>}</main>{settings&&<SettingsPanel progress={progress} setProgress={setProgress} onClose={()=>setSettings(false)}/>}</div>
}
function HellGate({onEnter}:{onEnter:()=>void}){return <main className="gate-shell"><div className="ember-field" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><header className="brand"><Flame size={20}/><span>PYTHON <b>FROM HELL</b></span><small>v1.0 // PLAYABLE DESCENT</small></header><section className="gate-content"><div className="eyebrow"><span className="pulse"/> DEVELOPER HELL // GATE 01</div><h1>WELCOME TO<br/><em>PYTHON FROM HELL.</em></h1><p className="hook">Python is easy.</p><p className="pause">That's what they told you.</p><button className="primary-cta" onClick={onEnter}>ENTER HELL <ChevronRight size={20}/></button><p className="microcopy">No fake progress. No fake buttons. The runtime judges your code.</p></section><footer className="gate-footer"><span>PYTHONSURA // MENTOR ONLINE</span><span>PYTHON RUNTIME: READY</span><span>12 LAYERS // 1 WAY OUT</span></footer></main>}
function Sidebar({view,unlocked,onNavigate}:{view:View;unlocked:number;onNavigate:(v:View)=>void}){return <aside className="sidebar"><div className="brand compact"><Flame size={20}/><span>PYTHON <b>FROM HELL</b></span></div><div className="layer-badge"><small>YOU ARE HERE</small><strong>LAYER {String(unlocked).padStart(2,'0')}</strong><span>{hellLayers[unlocked-1]?.name??'THE CORE'}</span></div><nav>{nav.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} aria-current={view===id?'page':undefined} onClick={()=>onNavigate(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="mentor-mini"><div className="avatar">P</div><div><small>MENTOR</small><strong>PYTHONSURA</strong><span>online • judging</span></div></div></aside>}
function Topbar({progress,onSettings}:{progress:Progress;onSettings:()=>void}){return <header className="topbar"><div><p className="eyebrow">COMMAND NETWORK</p><h2>Good morning, <em>heretic.</em></h2></div><div className="top-stats"><span>LVL <b>{String(levelFromXp(progress.xp)).padStart(2,'0')}</b></span><span>XP <b>{progress.xp}</b></span><span>STREAK <b>{progress.streak}</b></span><button title="Settings" aria-label="Open game settings" onClick={onSettings}><Settings size={16}/></button></div></header>}
function CommandCenter({progress,unlocked,onLesson,onNavigate}:{progress:Progress;unlocked:number;onLesson:(id:string)=>void;onNavigate:(v:View)=>void}){const next=lessonCatalog.find(l=>!progress.completedLessons.includes(l.id))??lessonCatalog[lessonCatalog.length-1];const story=nextStoryEvent(progress.completedLessons.length);const records=Object.values(progress.attempts);const mastery=records.length?Math.round(records.reduce((a,b)=>a+b.mastery,0)/records.length):0;return <div className="page"><section className="hero-panel"><div><div className="eyebrow"><span className="pulse"/> NEXT MISSION</div><h1>{next.title}</h1><p>{next.brief}</p><div className="mission-meta"><span>{next.minutes} MIN</span><span>{next.difficulty}</span><span>+{XP_REWARDS.lesson} XP</span></div><button className="primary-cta small" onClick={()=>onLesson(next.id)}><Play size={15}/> START LESSON</button></div><CodePreview code={next.starterCode}/></section><div className="stat-grid"><Stat label="HELL LAYER" value={`0${unlocked}`} sub={hellLayers[unlocked-1]?.name??'THE CORE'}/><Stat label="SOUL LEVEL" value={String(levelFromXp(progress.xp)).padStart(2,'0')} sub="PYTHON INTERN"/><Stat label="XP TO NEXT" value={String(xpToNext(progress.xp))} sub="KEEP DIGGING"/><Stat label="MASTERY" value={`${mastery}%`} sub={`${progress.completedLessons.length} LESSONS CLEARED`}/></div><div className="feature-grid"><Feature icon={BookOpen} title="WHAT SHOULD I DO NEXT?" text="Adaptive route starts at the next unfinished lesson." action="OPEN MISSION" onClick={()=>onLesson(next.id)}/><Feature icon={Bug} title="DEBUGGING DUNGEON" text="Repair real broken programs under a behavioral check." action="ENTER DUNGEON" onClick={()=>onNavigate('debugging')}/><Feature icon={Swords} title="BOSS BATTLES" text="Every phase now requires a coding clear." action="ENTER CHAMBER" onClick={()=>onNavigate('bosses')}/></div><div className="panel story-panel"><div className="panel-title"><span>STORY SIGNAL</span><small>{story?.id??'CORE'}</small></div><h3>{story?.title??'The Core is listening.'}</h3><p>{story?.text??'Keep descending. The runtime has not forgotten you.'}</p></div></div>}
function Stat({label,value,sub}:{label:string;value:string;sub:string}){return <div className="stat"><small>{label}</small><strong>{value}</strong><span>{sub}</span></div>}
function Feature({icon:Icon,title,text,action,onClick}:{icon:LucideIcon;title:string;text:string;action:string;onClick:()=>void}){return <button className="feature" onClick={onClick}><Icon/><small>{title}</small><p>{text}</p><b>{action} <ChevronRight size={14}/></b></button>}
function CodePreview({code}:{code:string}){return <div className="lesson-terminal"><div className="terminal-top"><span/><span/><span/><label>lesson.py</label></div><pre>{code}</pre></div>}
function Curriculum({unlocked,completed,onLesson}:{unlocked:number;completed:string[];onLesson:(id:string)=>void}){return <div className="page"><div className="section-heading"><div><div className="eyebrow">THE DESCENT</div><h1>12 LAYERS OF HELL</h1></div><span>{completed.length} LESSONS CLEARED</span></div><div className="curriculum-grid">{hellLayers.map(layer=>{const ls=lessonCatalog.filter(l=>l.layer===layer.number);const cleared=ls.filter(l=>completed.includes(l.id)).length;return <article key={layer.id} className={`layer-card ${layer.number<=unlocked?'open':'locked'}`}><div className="layer-number">{String(layer.number).padStart(2,'0')}</div><div><small>LAYER {String(layer.number).padStart(2,'0')} · {cleared}/{ls.length}</small><h3>{layer.name}</h3><p>{layer.tagline}</p><div className="topic-list">{layer.topics.map(t=><span key={t}>{t}</span>)}</div>{layer.number<=unlocked?<button onClick={()=>{const id=ls.find(l=>!completed.includes(l.id))?.id??ls[0]?.id;if(id)onLesson(id)}}>ENTER LAYER <ChevronRight size={14}/></button>:<span className="locked-label">LOCKED — CLEAR CURRENT LAYER</span>}</div></article>})}</div></div>}
function useRunner(){const [runner]=useState(()=>new PythonRunner());useEffect(()=>()=>runner.dispose(),[runner]);return runner}
function CodingArena({progress,setProgress}:{progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>}){const [code,setCode]=useState('def greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("heretic"))');const [out,setOut]=useState('');const [running,setRunning]=useState(false);const rewarded=progress.codingRewards>0;const runner=useRunner();const run=async()=>{if(running)return;setRunning(true);const r=await runner.run(code);if(r.cancelled){setRunning(false);return}setOut(r.error?`ERROR\n${r.error}`:r.stdout||'(no output)');setRunning(false);if(!r.error&&!rewarded)setProgress(p=>claimCodingReward(p))};const stop=()=>{if(running)runner.stop()};return <div className="page"><div className="section-heading"><div><div className="eyebrow">CODING ARENA</div><h1>WRITE. RUN. SURVIVE.</h1></div><span>{rewarded?'FIRST PRACTICE REWARD CLAIMED':'+20 XP FOR FIRST CLEAN RUN'}</span></div><div className="arena"><textarea spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} aria-label="Coding arena editor" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void run()}}}/><div className="arena-side"><div className="editor-actions">{running?<button className="run-btn" onClick={stop}><Square size={14}/> STOP</button>:<button className="run-btn" onClick={()=>void run()}>RUN PYTHON <Play size={15}/></button>}<button onClick={()=>{setCode('');setOut('')}}><RotateCcw size={14}/> CLEAR</button></div><div className="terminal-output"><div>OUTPUT</div><pre>{out||'Your output will appear here.'}</pre></div></div></div></div>}
function DebuggingDungeon({progress,setProgress}:{progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>}){const [index,setIndex]=useState(0);const current=debuggingCases[index];const [code,setCode]=useState(current.brokenCode);const [result,setResult]=useState('');const [running,setRunning]=useState(false);const cleared=progress.debugRewards.includes(current.id);const runner=useRunner();useEffect(()=>{setCode(current.brokenCode);setResult('')},[current.id,current.brokenCode]);const run=async()=>{if(running||cleared)return;setRunning(true);const r=await runner.run(code);if(r.cancelled){setRunning(false);return}setResult(r.error?`ERROR\n${r.error}`:r.stdout||'(no output)');setRunning(false);if(!r.error&&current.successCheck(r.stdout,code))setProgress(p=>claimDebugReward(p,current.id))};const stop=()=>{if(running)runner.stop()};return <div className="page"><div className="section-heading"><div><div className="eyebrow">DEBUGGING DUNGEON // CASE {String(index+1).padStart(2,'0')}</div><h1>{current.title}</h1></div><button className="back-btn" onClick={()=>setIndex(i=>(i+1)%debuggingCases.length)}>NEXT CASE →</button></div><p className="lead">{current.brief} <b>{current.bugType}</b></p><div className="debug-grid"><section className="broken"><div className="trace-label">BROKEN PROGRAM</div><textarea spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} aria-label={`${current.title} Python program`}/><div className="editor-actions">{running?<button className="run-btn" onClick={stop}><Square size={14}/> STOP</button>:<button className="run-btn" disabled={cleared} onClick={()=>void run()}>{cleared?'CASE CLEARED':'RUN & INSPECT'}</button>}</div><div className="terminal-output"><div>TRACE</div><pre>{result||'Reproduce the failure first.'}</pre></div></section><section className="method"><span>PYTHONSURA // DEBUGGING METHOD</span><h2>Don't patch the symptom.</h2><ol>{current.method.map(step=><li key={step}>{step}</li>)}</ol><div className="hint-box"><span>HINT</span><p>{current.hint}</p></div></section></div></div>}
function BossChamber({progress,unlocked,setProgress}:{progress:Progress;unlocked:number;setProgress:Dispatch<SetStateAction<Progress>>}){const boss=bosses.find(b=>b.layer<=unlocked&&!progress.completedBosses.includes(b.id));const phaseIndex=boss?Math.min(progress.bossPhaseProgress[boss.id]??0,boss.phases.length-1):0;const phase=boss?.phases[phaseIndex] as BossPhase|undefined;const [code,setCode]=useState(phase?.starterCode??'');const [output,setOutput]=useState('');const [message,setMessage]=useState('');const [running,setRunning]=useState(false);const [cleared,setCleared]=useState(false);const runner=useRunner();useEffect(()=>{setCode(phase?.starterCode??'');setOutput('');setMessage('');setCleared(false)},[boss?.id,phaseIndex]);if(!boss)return <div className="page"><div className="panel"><h2>NO BOSS AVAILABLE.</h2><p>Clear the current layer. The demons are educationally patient.</p></div></div>;const run=async()=>{if(running||cleared)return;setRunning(true);const visible=await runner.run(code);if(visible.cancelled){setRunning(false);setMessage('Execution cancelled. No phase progress was recorded.');return}const judged=await evaluateBossPhase(phase!,code,visible,runner);setOutput(visible.error?`ERROR\n${visible.error}`:visible.stdout||'(no output)');setMessage(judged.reason);setCleared(judged.passed);setRunning(false)};const stop=()=>{if(running)runner.stop()};const advance=()=>{if(!cleared)return;if(phaseIndex<boss.phases.length-1){setProgress(p=>setBossPhase(p,boss.id,phaseIndex+1));setCleared(false)}else setProgress(p=>claimBossReward(p,boss.id,boss.rewardXp))};return <div className="page"><div className="section-heading"><div><div className="eyebrow">BOSS CHAMBER // LAYER {boss.layer}</div><h1>{boss.name}</h1></div><span>PHASE {phaseIndex+1}/{boss.phases.length}</span></div><div className="boss-panel"><div className="boss-sigil"><Swords size={60}/><span>{boss.name}</span></div><div><div className="eyebrow">{boss.title}</div><p>{boss.intro}</p><h2>{phase!.name}</h2><p>{phase!.objective}</p><small>CONCEPT // {phase!.concept}</small><textarea className="boss-editor" spellCheck={false} value={code} onChange={e=>{setCode(e.target.value);setCleared(false)}} aria-label="Boss phase Python code"/><div className="editor-actions">{running?<button className="run-btn" onClick={stop}><Square size={14}/> STOP</button>:<button className="run-btn" disabled={cleared} onClick={()=>void run()}>{cleared?'PHASE CLEARED':'RUN CHALLENGE'} <Play size={14}/></button>}<button onClick={()=>setCode(phase!.starterCode)}><RotateCcw size={14}/> RESET</button></div><div className="terminal-output"><div>JUDGEMENT</div><pre>{output||'The boss is waiting.'}</pre></div>{message&&<div className={`feedback ${cleared?'success-row':''}`}>{message}</div>}<button className="primary-cta small" disabled={!cleared} onClick={advance}>{phaseIndex+1===boss.phases.length?'DEAL FINAL BLOW':'ENTER NEXT PHASE'} <ChevronRight size={15}/></button></div></div></div>}
function InterviewArena({progress,setProgress}:{progress:Progress;setProgress:Dispatch<SetStateAction<Progress>>}){const done=progress.interview.round>=interviewQuestions.length;const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState('');if(done)return <div className="page"><div className="panel"><div className="eyebrow">ARENA COMPLETE</div><h2>YOU SURVIVED THE INTERVIEW DEMON.</h2><p>Rank: <b>{progress.interview.rank}</b> · Score: <b>{progress.interview.score}/{interviewQuestions.length*2}</b></p>{!progress.interview.rewarded&&<button className="primary-cta small" onClick={()=>setProgress(p=>claimInterviewReward(p))}>CLAIM SURVIVAL REWARD +50 XP</button>}</div></div>;const q=interviewQuestions[progress.interview.round];const submit=()=>{const normalized=answer.toLowerCase();const hits=q.expectedPoints.filter(point=>point.toLowerCase().split(/\s+/).filter(w=>w.length>4).every(w=>normalized.includes(w))).length;setFeedback(hits>=2?`${q.roast} Strong answer.`:`${q.roast} Too thin. Explain the mechanism.`);setProgress(p=>{const score=Math.min(2,hits);const total=p.interview.score+score;const round=Math.min(p.interview.round+1,interviewQuestions.length);const pct=total/(interviewQuestions.length*2);const rank=pct>=.8?'PYTHON OVERLORD':pct>=.6?'PYTHON HERETIC':pct>=.4?'HELL TOURIST':'PYTHON INTERN';return{...p,interview:{...p.interview,round,score:total,rank},achievements:round===interviewQuestions.length?grantAchievement(p.achievements,ACHIEVEMENTS.INTERVIEW_SURVIVOR):p.achievements}});setAnswer('')};return <div className="page"><div className="section-heading"><div><div className="eyebrow">INTERVIEW BATTLE ARENA</div><h1>THE INTERVIEWER DEMON</h1></div><span>ROUND {progress.interview.round+1}/{interviewQuestions.length}</span></div><div className="interview-card"><div className="demon"><Shield/><span>{q.tier.toUpperCase()}</span></div><h2>{q.prompt}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Answer with reasoning, not vibes…"/><button className="primary-cta small" disabled={!answer.trim()} onClick={submit}>SUBMIT ANSWER <ChevronRight size={15}/></button><p>{feedback||`Follow-up: ${q.followUp}`}</p></div></div>}
